/**
 * Shell completion script generators for payway-sdk.
 *
 * All four dialects are emitted from the same flattened command tree
 * (see flattenTree), so the scripts can never drift from the live CLI
 * registry. Semantics locked by spec §4.1:
 *   - non-dash completion at a path → child command names
 *   - dash completion at a path → that path's flags ∪ inherited root globals
 *   - `--help` everywhere; `--version` only at the root (registered natively
 *     by `.version()` on the root, deduped here)
 * Descriptions are shell-escaped per dialect; word lists never need escaping
 * (command names and flags are [a-z0-9-_]).
 */

import type { CompletionCommand, CompletionOption } from './introspect.js';

export type CompletionShell = 'bash' | 'zsh' | 'fish' | 'powershell';

export const COMPLETION_SHELLS: readonly CompletionShell[] = ['bash', 'zsh', 'fish', 'powershell'];

export interface FlatEntry {
  /** Space-joined command chain; '' is the root. */
  path: string;
  children: CompletionCommand[];
  options: CompletionOption[];
}

const HELP_OPTION: CompletionOption = { long: '--help', description: 'Show help' };

/** Flattens the tree into path-keyed entries, root first, breadth-first. */
export function flattenTree(root: CompletionCommand): FlatEntry[] {
  const entries: FlatEntry[] = [];
  const visit = (node: CompletionCommand, path: string): void => {
    const options: CompletionOption[] = [];
    const seen = new Set<string>();
    for (const option of node.options) {
      if (option.long && seen.has(option.long)) continue;
      if (option.long) seen.add(option.long);
      options.push(option);
    }
    entries.push({ path, children: node.subcommands, options });
    for (const sub of node.subcommands) visit(sub, path ? `${path} ${sub.name}` : sub.name);
  };
  visit(root, '');
  return entries;
}

/**
 * Flags for a path: own options ∪ inherited root globals (non-root entries),
 * plus a synthetic `--help` (commander only materializes it during help
 * rendering, never in `command.options`). `--version` stays root-only.
 * Deduped by long flag.
 */
function flagOptions(entry: FlatEntry, rootOptions: CompletionOption[]): CompletionOption[] {
  const globals = entry.path === '' ? [] : rootOptions.filter((option) => option.long !== '--version');
  const merged: CompletionOption[] = entry.path === '' ? [...entry.options] : [...entry.options, ...globals];
  merged.push(HELP_OPTION);
  const seen = new Set<string>();
  return merged.filter((option) => {
    if (!option.long || seen.has(option.long)) return false;
    seen.add(option.long);
    return true;
  });
}

function flagTokens(options: CompletionOption[]): string {
  return options
    .map((option) => [option.short, option.long].filter(Boolean).join(' '))
    .join(' ');
}

/** POSIX single-quote escaping (bash/zsh/fish description strings). */
function shQuote(text: string): string {
  return `'${text.replaceAll("'", `'\\''`)}'`;
}

function pathCaseGuard(entry: FlatEntry): string {
  return entry.path === '' ? '' : entry.path;
}

// --- bash -------------------------------------------------------------------

export function generateBashScript(root: CompletionCommand): string {
  const entries = flattenTree(root);
  const [rootEntry] = entries;
  const rootFlags = flagOptions(rootEntry, []);
  const lines: string[] = [
    '# bash completion for payway-sdk (generated by `payway-sdk completions bash`; do not edit)',
    '# Install: source this file from ~/.bashrc',
    '_payway_sdk() {',
    '  local cur="${COMP_WORDS[COMP_CWORD]}"',
    '  local path=""',
    '  local i w',
    '  for ((i = 1; i < COMP_CWORD; i++)); do',
    '    w="${COMP_WORDS[i]}"',
    '    if [[ "$w" == -* ]]; then continue; fi',
    '    case "$path" in',
  ];
  for (const entry of entries) {
    if (entry.children.length === 0) continue;
    const names = entry.children.map((child) => child.name).join('|');
    const action = entry.path === '' ? 'path="$w"' : 'path="$path $w"';
    lines.push(`      "${pathCaseGuard(entry)}") case "$w" in ${names}) ${action};; esac ;;`);
  }
  lines.push('    esac');
  lines.push('  done');
  lines.push('  if [[ "$cur" == -* ]]; then');
  lines.push('    case "$path" in');
  for (const entry of entries) {
    const flags = flagTokens(flagOptions(entry, rootFlags));
    lines.push(`      "${pathCaseGuard(entry)}") COMPREPLY=( $(compgen -W "${flags}" -- "$cur") ) ;;`);
  }
  lines.push('    esac');
  lines.push('  else');
  lines.push('    case "$path" in');
  for (const entry of entries) {
    if (entry.children.length === 0) continue;
    const names = entry.children.map((child) => child.name).join(' ');
    lines.push(`      "${pathCaseGuard(entry)}") COMPREPLY=( $(compgen -W "${names}" -- "$cur") ) ;;`);
  }
  lines.push('    esac');
  lines.push('  fi');
  lines.push('}');
  lines.push('complete -F _payway_sdk payway-sdk');
  return lines.join('\n');
}

// --- zsh --------------------------------------------------------------------

export function generateZshScript(root: CompletionCommand): string {
  const entries = flattenTree(root);
  const [rootEntry] = entries;
  const rootFlags = flagOptions(rootEntry, []);
  const lines: string[] = [
    '#compdef payway-sdk',
    '# zsh completion for payway-sdk (generated by `payway-sdk completions zsh`; do not edit)',
    '# Install: source this file from ~/.zshrc (after compinit)',
    '_payway_sdk() {',
    '  local cur="$words[CURRENT]"',
    '  local path=""',
    '  local i w',
    '  for (( i = 2; i < CURRENT; i++ )); do',
    '    w="${words[i]}"',
    '    if [[ "$w" == -* ]]; then continue; fi',
    '    case "$path" in',
  ];
  for (const entry of entries) {
    if (entry.children.length === 0) continue;
    const names = entry.children.map((child) => child.name).join('|');
    const action = entry.path === '' ? 'path="$w"' : 'path="$path $w"';
    lines.push(`      "${pathCaseGuard(entry)}") case "$w" in (${names}) ${action} ;; esac ;;`);
  }
  lines.push('    esac');
  lines.push('  done');
  lines.push('  if [[ "$cur" == -* ]]; then');
  lines.push('    case "$path" in');
  for (const entry of entries) {
    const flags = flagOptions(entry, rootFlags)
      .map((option) => `${option.long}:${shQuote(option.description)}`)
      .join(' ');
    lines.push(`      "${pathCaseGuard(entry)}")`);
    lines.push('        local -a opts');
    lines.push(`        opts=(${flags})`);
    lines.push(`        _describe -o option opts`);
    lines.push('        ;;');
  }
  lines.push('    esac');
  lines.push('  else');
  lines.push('    case "$path" in');
  for (const entry of entries) {
    if (entry.children.length === 0) continue;
    const cmds = entry.children.map((child) => `${child.name}:${shQuote(child.description)}`).join(' ');
    lines.push(`      "${pathCaseGuard(entry)}")`);
    lines.push('        local -a cmds');
    lines.push(`        cmds=(${cmds})`);
    lines.push(`        _describe 'command' cmds`);
    lines.push('        ;;');
  }
  lines.push('    esac');
  lines.push('  fi');
  lines.push('}');
  lines.push('compdef _payway_sdk payway-sdk');
  return lines.join('\n');
}

// --- fish -------------------------------------------------------------------

function fishChildCondition(entry: FlatEntry): string {
  if (entry.path === '') return '__fish_use_subcommand';
  const chain = entry.path
    .split(' ')
    .map((segment) => `__fish_seen_subcommand_from ${segment}`)
    .join('; and ');
  const siblings = entry.children.map((child) => `not __fish_seen_subcommand_from ${child.name}`).join('; and ');
  return siblings ? `${chain}; and ${siblings}` : chain;
}

export function generateFishScript(root: CompletionCommand): string {
  const entries = flattenTree(root);
  const [rootEntry] = entries;
  const rootFlags = flagOptions(rootEntry, []);
  const lines: string[] = [
    '# fish completions for payway-sdk (generated by `payway-sdk completions fish`; do not edit)',
    '# Install: save as ~/.config/fish/completions/payway-sdk.fish',
    'complete -c payway-sdk -f',
  ];
  // Root children get the subcommand guard; deeper children get the
  // parent-chain guard plus not-seen-sibling guards so a deeper path never
  // re-offers shallower completions.
  for (const entry of entries) {
    for (const child of entry.children) {
      lines.push(
        `complete -c payway-sdk -n '${fishChildCondition(entry)}' -a ${shQuote(child.name)} -d ${shQuote(child.description)}`,
      );
    }
  }
  for (const entry of entries) {
    const flagScope =
      entry.path === ''
        ? ''
        : `-n '${entry.path.split(' ').map((segment) => `__fish_seen_subcommand_from ${segment}`).join('; and ')}'`;
    for (const option of flagOptions(entry, rootFlags)) {
      const short = option.short ? ` -s ${option.short.replace(/^-/, '')}` : '';
      const desc = option.description ? ` -d ${shQuote(option.description)}` : '';
      lines.push(
        `complete -c payway-sdk ${flagScope} -l ${option.long.replace(/^--/, '')}${short}${desc}`
          .replace(/\s+/g, ' ')
          .trimEnd(),
      );
    }
  }
  return lines.join('\n');
}

// --- powershell ---------------------------------------------------------------

export function generatePowerShellScript(root: CompletionCommand): string {
  const entries = flattenTree(root);
  const [rootEntry] = entries;
  const rootFlags = flagOptions(rootEntry, []);
  const ps = (text: string): string => `'${text.replaceAll("'", "''")}'`;
  const psPath = (entry: FlatEntry): string => (entry.path === '' ? "''" : ps(entry.path));
  const lines: string[] = [
    '# PowerShell argument completer for payway-sdk (generated by `payway-sdk completions powershell`; do not edit)',
    '# Install: dot-source this file from your $PROFILE',
    `Register-ArgumentCompleter -CommandName 'payway-sdk' -Native -ScriptBlock {`,
    '  param($wordToComplete, $commandAst, $cursorPosition)',
    `  $words = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { "$_" })`,
    `  $path = ''`,
    '  foreach ($w in $words) {',
    `    if ($w -like '-*') { continue }`,
    '    switch ($path) {',
  ];
  for (const entry of entries) {
    if (entry.children.length === 0) continue;
    const names = entry.children.map((child) => ps(child.name)).join(', ');
    if (entry.path === '') {
      lines.push(`      '' { if (@(${names}) -contains $w) { $path = $w } }`);
    } else {
      lines.push(`      ${ps(entry.path)} { if (@(${names}) -contains $w) { $path = "$path $w" } }`);
    }
  }
  lines.push('      default { }');
  lines.push('    }');
  lines.push('  }');
  lines.push('  $candidates = @()');
  lines.push(`  if ($wordToComplete -like '-*') {`);
  lines.push('    switch ($path) {');
  for (const entry of entries) {
    const flags = flagOptions(entry, rootFlags)
      .map((option) => option.long)
      .map(ps)
      .join(', ');
    lines.push(`      ${psPath(entry)} { $candidates = @(${flags}) }`);
  }
  lines.push('      default { }');
  lines.push('    }');
  lines.push('  } else {');
  lines.push('    switch ($path) {');
  for (const entry of entries) {
    if (entry.children.length === 0) continue;
    const names = entry.children.map((child) => ps(child.name)).join(', ');
    lines.push(`      ${psPath(entry)} { $candidates = @(${names}) }`);
  }
  lines.push('      default { }');
  lines.push('    }');
  lines.push('  }');
  lines.push('  $candidates |');
  lines.push('    Where-Object { $_ -like "$wordToComplete*" } |');
  lines.push(`    ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }`);
  lines.push('}');
  return lines.join('\n');
}

// --- dispatcher ---------------------------------------------------------------

export function generateCompletionScript(shell: CompletionShell, root: CompletionCommand): string {
  switch (shell) {
    case 'bash':
      return generateBashScript(root);
    case 'zsh':
      return generateZshScript(root);
    case 'fish':
      return generateFishScript(root);
    case 'powershell':
      return generatePowerShellScript(root);
    default:
      throw new Error(`Unknown shell "${String(shell)}". Known shells: ${COMPLETION_SHELLS.join(', ')}.`);
  }
}
