# PowerShell argument completer for payway-sdk (generated by `payway-sdk completions powershell`; do not edit)
# Install: dot-source this file from your $PROFILE
Register-ArgumentCompleter -CommandName 'payway-sdk' -Native -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $words = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { "$_" })
  $path = ''
  foreach ($w in $words) {
    if ($w -like '-*') { continue }
    switch ($path) {
      '' { if (@('payment-link', 'generate-qr') -contains $w) { $path = $w } }
      'payment-link' { if (@('create') -contains $w) { $path = "$path $w" } }
      default { }
    }
  }
  $candidates = @()
  if ($wordToComplete -like '-*') {
    switch ($path) {
      '' { $candidates = @('--version', '--profile', '--help') }
      'payment-link' { $candidates = @('--profile', '--help') }
      'payment-link create' { $candidates = @('--title', '--profile', '--help') }
      'generate-qr' { $candidates = @('--amount', '--profile', '--help') }
      default { }
    }
  } else {
    switch ($path) {
      '' { $candidates = @('payment-link', 'generate-qr') }
      'payment-link' { $candidates = @('create') }
      default { }
    }
  }
  $candidates |
    Where-Object { $_ -like "$wordToComplete*" } |
    ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
