# fish completions for payway-sdk (generated by `payway-sdk completions fish`; do not edit)
# Install: save as ~/.config/fish/completions/payway-sdk.fish
complete -c payway-sdk -f
complete -c payway-sdk -n '__fish_use_subcommand' -a 'payment-link' -d 'Payment links'
complete -c payway-sdk -n '__fish_use_subcommand' -a 'generate-qr' -d 'QR'
complete -c payway-sdk -n '__fish_seen_subcommand_from payment-link; and not __fish_seen_subcommand_from create' -a 'create' -d 'Create'
complete -c payway-sdk -l version -s V -d 'output the version number'
complete -c payway-sdk -l profile -d 'Use a saved profile'
complete -c payway-sdk -l help -d 'Show help'
complete -c payway-sdk -n '__fish_seen_subcommand_from payment-link' -l profile -d 'Use a saved profile'
complete -c payway-sdk -n '__fish_seen_subcommand_from payment-link' -l help -d 'Show help'
complete -c payway-sdk -n '__fish_seen_subcommand_from payment-link; and __fish_seen_subcommand_from create' -l title -d 'Title'
complete -c payway-sdk -n '__fish_seen_subcommand_from payment-link; and __fish_seen_subcommand_from create' -l profile -d 'Use a saved profile'
complete -c payway-sdk -n '__fish_seen_subcommand_from payment-link; and __fish_seen_subcommand_from create' -l help -d 'Show help'
complete -c payway-sdk -n '__fish_seen_subcommand_from generate-qr' -l amount -s a -d 'Amount'
complete -c payway-sdk -n '__fish_seen_subcommand_from generate-qr' -l profile -d 'Use a saved profile'
complete -c payway-sdk -n '__fish_seen_subcommand_from generate-qr' -l help -d 'Show help'
