#compdef payway-sdk
# zsh completion for payway-sdk (generated by `payway-sdk completions zsh`; do not edit)
# Install: source this file from ~/.zshrc (after compinit)
_payway_sdk() {
  local cur="$words[CURRENT]"
  local path=""
  local i w
  for (( i = 2; i < CURRENT; i++ )); do
    w="${words[i]}"
    if [[ "$w" == -* ]]; then continue; fi
    case "$path" in
      "") case "$w" in (payment-link|generate-qr) path="$w" ;; esac ;;
      "payment-link") case "$w" in (create) path="$path $w" ;; esac ;;
    esac
  done
  if [[ "$cur" == -* ]]; then
    case "$path" in
      "")
        local -a opts
        opts=(--version:'output the version number' --profile:'Use a saved profile' --help:'Show help')
        _describe -o option opts
        ;;
      "payment-link")
        local -a opts
        opts=(--profile:'Use a saved profile' --help:'Show help')
        _describe -o option opts
        ;;
      "payment-link create")
        local -a opts
        opts=(--title:'Title' --profile:'Use a saved profile' --help:'Show help')
        _describe -o option opts
        ;;
      "generate-qr")
        local -a opts
        opts=(--amount:'Amount' --profile:'Use a saved profile' --help:'Show help')
        _describe -o option opts
        ;;
    esac
  else
    case "$path" in
      "")
        local -a cmds
        cmds=(payment-link:'Payment links' generate-qr:'QR')
        _describe 'command' cmds
        ;;
      "payment-link")
        local -a cmds
        cmds=(create:'Create')
        _describe 'command' cmds
        ;;
    esac
  fi
}
compdef _payway_sdk payway-sdk
