# bash completion for payway-sdk (generated by `payway-sdk completions bash`; do not edit)
# Install: source this file from ~/.bashrc
_payway_sdk() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local path=""
  local i w
  for ((i = 1; i < COMP_CWORD; i++)); do
    w="${COMP_WORDS[i]}"
    if [[ "$w" == -* ]]; then continue; fi
    case "$path" in
      "") case "$w" in payment-link|generate-qr) path="$w";; esac ;;
      "payment-link") case "$w" in create) path="$path $w";; esac ;;
    esac
  done
  if [[ "$cur" == -* ]]; then
    case "$path" in
      "") COMPREPLY=( $(compgen -W "-V --version --profile --help" -- "$cur") ) ;;
      "payment-link") COMPREPLY=( $(compgen -W "--profile --help" -- "$cur") ) ;;
      "payment-link create") COMPREPLY=( $(compgen -W "--title --profile --help" -- "$cur") ) ;;
      "generate-qr") COMPREPLY=( $(compgen -W "-a --amount --profile --help" -- "$cur") ) ;;
    esac
  else
    case "$path" in
      "") COMPREPLY=( $(compgen -W "payment-link generate-qr" -- "$cur") ) ;;
      "payment-link") COMPREPLY=( $(compgen -W "create" -- "$cur") ) ;;
    esac
  fi
}
complete -F _payway_sdk payway-sdk
