/**
 * Golden-vector runner (audit DX-TEST-001,
 * docs/project/2026-10-05-dx-platform-audit-pass2.md §27, §47).
 *
 * The fixtures under fixtures/vectors/hmac/ are generated by
 * scripts/generate/gen-golden-vectors.ts, which drives the LIVE signing code
 * (domain factories + generateHmac) with fixed inputs and the repo test key.
 * This suite re-computes every pinned hash through the public code path and
 * fails — with regeneration instructions — on any drift:
 *
 * 1. FIXTURE LINT   — schema, digest shapes, sanitization (no key material,
 *                     no credential-shaped strings) per vector file.
 * 2. GOLDEN RECOMPUTE — generateHmac(canonicalPayload, fieldOrder, key,
 *                     encoding, algorithm) must equal the pinned expectedHash,
 *                     and the reconstructed preimage must match the recorded
 *                     one (sha256-compared so failure output never dumps key
 *                     material or full payloads).
 * 3. FAMILY PINNING — a vector naming a *_HASH_FIELDS/HMAC_FIELDS export must
 *                     carry exactly that export's field order (bidirectional
 *                     pinning, §27.3 #2: neither side can drift alone). The
 *                     export set is collected DYNAMICALLY from the modules,
 *                     never hardcoded.
 * 4. COVERAGE GATE  — every hash-field family export and every HASH_ORDER_HINTS
 *                     composition must be pinned by >= 1 vector; inline family
 *                     vectors must agree with their live hint. Negative
 *                     controls exercise the coverage logic on synthetic input.
 * 5. PAYOUT REGRESSION — synthetic proof that the machinery catches a payout
 *                     field-order reorder and a hex->base64 encoding
 *                     regression (PO-003) without mutating real constants,
 *                     plus a live-code capture pinning the payout domain's
 *                     actual hex encoding.
 *
 * Intentional signing change? Regenerate with
 * `npx tsx scripts/generate/gen-golden-vectors.ts` and commit fixtures + code
 * together (append-only policy, §27.3 #1).
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it, vi } from 'vitest';

import { generateHmac } from '../auth.js';
import { PayWayConfigError } from '../errors.js';
import * as clientModule from '../client.js';
import { HASH_ORDER_HINTS, type PayWayConfig } from '../client.js';
import { ENDPOINTS } from '../constants.js';
import * as checkoutModule from '../domains/checkout.js';
import * as credentialsOnFileModule from '../domains/credentials-on-file.js';
import { createPayoutDomain } from '../domains/payout.js';
import * as qrModule from '../domains/qr.js';
import { generateTestRsaKeyPair } from '../test/test-utils.js';

/**
 * The repo's standard TEST fixture key (src/__tests__/cli.test.ts) — the same
 * value the generator used, never a real credential. Duplicated from the
 * generator ON PURPOSE: importing the generator module would execute it.
 */
const GOLDEN_TEST_API_KEY = 'test-api-key-123456789012';
const GOLDEN_KEY_ALIAS = 'golden-vector-test-key';

const VECTORS_DIR = fileURLToPath(new URL('../../fixtures/vectors/hmac/', import.meta.url));

interface GoldenVector {
  vectorId: string;
  operation: string;
  endpoint: string;
  description: string;
  hashFieldsFamily: string;
  fieldOrder: string[];
  fieldOrderSource: string;
  hashAlgorithm: 'sha512' | 'sha256';
  hashEncoding: 'base64' | 'hex';
  keyAlias: string;
  canonicalPayload: Record<string, unknown>;
  preimage: string;
  preimageSha256: string;
  expectedHash: string;
  normalization: Array<{ field: string; rule: string; note?: string }>;
  context?: Record<string, unknown>;
  provenance: { generatedBy: string; verifiedAgainst: string };
}

/** Load every vector fixture once (INDEX.json excluded). */
function loadVectors(): Array<{ file: string; text: string; vector: GoldenVector }> {
  return readdirSync(VECTORS_DIR)
    .filter((file) => file.endsWith('.json') && file !== 'INDEX.json')
    .sort()
    .map((file) => {
      const text = readFileSync(path.join(VECTORS_DIR, file), 'utf8');
      return { file, text, vector: JSON.parse(text) as GoldenVector };
    });
}

const vectors = loadVectors();
const vectorById = new Map(vectors.map((entry) => [entry.vector.vectorId, entry.vector]));

// ── Pure helpers (the "machinery" the synthetic regression tests exercise) ──

/** Mirrors generateHmac's canonicalization for the preimage reconstruction check. */
function buildPreimage(payload: Record<string, unknown>, fieldOrder: string[]): string {
  return fieldOrder
    .map((field) => {
      const val = payload[field];
      if (val === undefined || val === null) return '';
      return String(val);
    })
    .join('');
}

function sha256Hex(value: string): string {
  return createHash('sha256').update(value, 'utf8').digest('hex');
}

interface VectorEvaluation {
  ok: boolean;
  /** Present only when ok === false. Never contains key material. */
  failure?: {
    kind: 'digest_shape' | 'preimage_mismatch' | 'hash_mismatch';
    firstDifferingField?: { field: string; position: number };
    expectedPreimageSha256?: string;
    actualPreimageSha256?: string;
    detail: string;
  };
}

function digestByteLength(vector: Pick<GoldenVector, 'hashAlgorithm'>): number {
  return vector.hashAlgorithm === 'sha512' ? 64 : 32;
}

function digestHasValidShape(vector: Pick<GoldenVector, 'hashAlgorithm' | 'hashEncoding' | 'expectedHash'>): boolean {
  try {
    if (vector.hashEncoding === 'hex') {
      return /^[a-f0-9]+$/.test(vector.expectedHash) && vector.expectedHash.length === digestByteLength(vector) * 2;
    }
    return (
      /^[A-Za-z0-9+/]+={0,2}$/.test(vector.expectedHash) &&
      Buffer.from(vector.expectedHash, 'base64').length === digestByteLength(vector)
    );
  } catch {
    return false;
  }
}

/**
 * Map a preimage offset onto the field that owns it, walking the vector's
 * recorded field segments (undefined/null hash as '' — zero-width segments).
 */
function fieldAtPreimageOffset(vector: GoldenVector, offset: number): { field: string; position: number } {
  let segmentStart = 0;
  for (const field of vector.fieldOrder) {
    const val = vector.canonicalPayload[field];
    const segment = val === undefined || val === null ? '' : String(val);
    if (offset < segmentStart + segment.length) return { field, position: offset };
    segmentStart += segment.length;
  }
  return { field: vector.fieldOrder[vector.fieldOrder.length - 1] ?? '?', position: offset };
}

/**
 * Recompute a vector's hash through the real generateHmac and compare against
 * the pinned digest. Pure so the synthetic regression tests below can drive
 * the exact machinery that gates the real files.
 */
function evaluateVector(vector: GoldenVector, apiKey: string): VectorEvaluation {
  if (!digestHasValidShape(vector)) {
    return {
      ok: false,
      failure: {
        kind: 'digest_shape',
        detail: `expectedHash is not a valid ${vector.hashAlgorithm}/${vector.hashEncoding} digest`,
      },
    };
  }
  const actualPreimage = buildPreimage(vector.canonicalPayload, vector.fieldOrder);
  const actualPreimageSha256 = sha256Hex(actualPreimage);
  if (actualPreimageSha256 !== vector.preimageSha256) {
    const at =
      actualPreimage === vector.preimage
        ? undefined
        : fieldAtPreimageOffset(vector, firstDifferenceOffset(vector.preimage, actualPreimage));
    return {
      ok: false,
      failure: {
        kind: 'preimage_mismatch',
        firstDifferingField: at,
        expectedPreimageSha256: vector.preimageSha256,
        actualPreimageSha256,
        detail: `reconstructed preimage differs from the pinned one${at ? ` in the segment owned by field "${at.field}"` : ''}`,
      },
    };
  }
  const actualHash = generateHmac(
    vector.canonicalPayload,
    vector.fieldOrder,
    apiKey,
    vector.hashEncoding,
    vector.hashAlgorithm,
  );
  if (actualHash !== vector.expectedHash) {
    return {
      ok: false,
      failure: {
        kind: 'hash_mismatch',
        expectedPreimageSha256: vector.preimageSha256,
        actualPreimageSha256,
        detail: `recomputed ${vector.hashAlgorithm}/${vector.hashEncoding} digest does not equal the pinned expectedHash`,
      },
    };
  }
  return { ok: true };
}

function firstDifferenceOffset(pinned: string, actual: string): number {
  let i = 0;
  const max = Math.min(pinned.length, actual.length);
  while (i < max && pinned[i] === actual[i]) i += 1;
  return i;
}

// ── Dynamic hash-field family export collection (never hardcoded) ───────────

const HASH_FAMILY_EXPORT_PATTERN = /_(?:HASH|HMAC)_FIELDS$/;

/**
 * Collect every `*_HASH_FIELDS` / `*_HMAC_FIELDS` export from the modules that
 * define hash-field families, by iterating the module namespaces — NOT by
 * hardcoding the family list. A new family export in any of these modules is
 * picked up automatically; the coverage gate then demands a vector for it.
 */
function collectHashFieldFamilyExports(): Record<string, readonly string[]> {
  const modules: Record<string, Record<string, unknown>> = {
    'src/client.ts': clientModule as unknown as Record<string, unknown>,
    'src/domains/checkout.ts': checkoutModule as unknown as Record<string, unknown>,
    'src/domains/qr.ts': qrModule as unknown as Record<string, unknown>,
    'src/domains/credentials-on-file.ts': credentialsOnFileModule as unknown as Record<string, unknown>,
  };
  const families: Record<string, readonly string[]> = {};
  for (const [file, mod] of Object.entries(modules)) {
    for (const key of Object.keys(mod)) {
      if (!HASH_FAMILY_EXPORT_PATTERN.test(key)) continue;
      const value = mod[key];
      if (!Array.isArray(value) || value.some((entry) => typeof entry !== 'string')) {
        throw new Error(`hash-field family export ${key} (${file}) must be a string array`);
      }
      families[key] = value as readonly string[];
    }
  }
  return families;
}

/**
 * Coverage logic over SYNTHETIC-friendly inputs: which family names lack a
 * pinning vector. Pure — the negative controls feed it fake families.
 */
function computeUncoveredFamilies(
  families: Record<string, readonly string[]>,
  pins: Array<{ hashFieldsFamily: string }>,
): string[] {
  const covered = new Set(pins.map((pin) => pin.hashFieldsFamily));
  return Object.keys(families)
    .filter((name) => !covered.has(name))
    .sort();
}

/** Hint compositions (dot-joined) that no vector pins, with their endpoint keys. */
function computeUncoveredHints(hints: Record<string, string>, pins: Array<{ fieldOrder: string[] }>): string[] {
  const pinned = new Set(pins.map((pin) => pin.fieldOrder.join('.')));
  return Object.entries(hints)
    .filter(([, composition]) => !pinned.has(composition))
    .map(([endpointKey]) => endpointKey)
    .sort();
}

/**
 * Inline-family consistency: every vector whose family is `inline:<endpoint>`
 * must name a real endpoint AND carry exactly that endpoint's live hint
 * composition (HASH_ORDER_HINTS is keyed by ENDPOINT PATH; resolve first).
 * This is the handshake that makes a LIVE field-order regression (code + hint
 * updated together, fixture left behind) fail the suite.
 */
function inlineFamilyMismatches(
  pins: Array<{ hashFieldsFamily: string; fieldOrder: string[] }>,
  hints: Record<string, string>,
  endpoints: Record<string, string>,
): Array<{ family: string; reason: 'unknown_endpoint' | 'hint_mismatch' }> {
  const mismatches: Array<{ family: string; reason: 'unknown_endpoint' | 'hint_mismatch' }> = [];
  for (const pin of pins) {
    if (!pin.hashFieldsFamily.startsWith('inline:')) continue;
    const key = pin.hashFieldsFamily.slice('inline:'.length);
    const endpointPath = endpoints[key];
    if (!endpointPath) {
      mismatches.push({ family: pin.hashFieldsFamily, reason: 'unknown_endpoint' });
      continue;
    }
    if (hints[endpointPath] !== pin.fieldOrder.join('.')) {
      mismatches.push({ family: pin.hashFieldsFamily, reason: 'hint_mismatch' });
    }
  }
  return mismatches;
}

// ── 1. Fixture lint ─────────────────────────────────────────────────────────

const FIELD_NAME_PATTERN = /^[a-z][a-z0-9_]*$/;
// Credential-shaped strings: a standalone 40-hex token (the audit's "known
// credential shape" — contiguous longer digests like the 64-hex
// preimageSha256 do NOT match), PEM private keys, AWS/GitHub/Stripe/Slack
// tokens, and the repo's real-credential file reference.
const CREDENTIAL_PATTERNS: Array<{ name: string; pattern: RegExp }> = [
  { name: 'standalone 40-hex secret', pattern: /(?:^|[^a-fA-F0-9])[a-fA-F0-9]{40}(?![a-fA-F0-9])/ },
  { name: 'PEM private key block', pattern: /-----BEGIN [A-Z ]*PRIVATE KEY-----/ },
  { name: 'AWS access key id', pattern: /AKIA[0-9A-Z]{16}/ },
  { name: 'GitHub token', pattern: /gh[pousr]_[A-Za-z0-9]{20,}/ },
  { name: 'Stripe secret key', pattern: /\bsk_live_/ },
  { name: 'Slack token', pattern: /xox[baprs]-/ },
  { name: 'sandbox credential file reference', pattern: /PaywAySandboxkey/ },
];

describe('golden-vector fixture lint', () => {
  it('found the expected vector corpus (>= 30 vector files)', () => {
    expect(vectors.length).toBeGreaterThanOrEqual(30);
  });

  it('INDEX.json is consistent with the vector files on disk', () => {
    const index = JSON.parse(readFileSync(path.join(VECTORS_DIR, 'INDEX.json'), 'utf8')) as {
      vectorCount: number;
      keyAlias: string;
      vectors: Array<{ vectorId: string; file: string }>;
    };
    expect(index.keyAlias).toBe(GOLDEN_KEY_ALIAS);
    expect(index.vectorCount).toBe(vectors.length);
    expect(index.vectors.map((entry) => entry.vectorId).sort()).toEqual(vectors.map((v) => v.vector.vectorId).sort());
    for (const entry of index.vectors) {
      expect(
        vectors.some((v) => v.file === entry.file && v.vector.vectorId === entry.vectorId),
        `INDEX entry ${entry.vectorId} points at ${entry.file}`,
      ).toBe(true);
    }
  });

  for (const { file, text, vector } of vectors) {
    it(`${file}: schema + required fields + digest shape`, () => {
      expect(vector.vectorId).toBeTypeOf('string');
      expect(vector.vectorId.length).toBeGreaterThan(0);
      expect(file).toBe(`${vector.vectorId}.json`);
      for (const field of ['operation', 'description', 'endpoint', 'hashFieldsFamily', 'fieldOrderSource'] as const) {
        expect(vector[field], `${file}: ${field}`).toBeTypeOf('string');
        expect(vector[field].length, `${file}: ${field} non-empty`).toBeGreaterThan(0);
      }
      expect(vector.fieldOrder.length, `${file}: fieldOrder non-empty`).toBeGreaterThan(0);
      for (const field of vector.fieldOrder) {
        expect(FIELD_NAME_PATTERN.test(field), `${file}: garbled field name "${field}"`).toBe(true);
      }
      expect(['sha512', 'sha256']).toContain(vector.hashAlgorithm);
      expect(['base64', 'hex']).toContain(vector.hashEncoding);
      // The fixtures carry the key ALIAS, never the key itself.
      expect(vector.keyAlias).toBe(GOLDEN_KEY_ALIAS);
      expect(vector.canonicalPayload).toBeTypeOf('object');
      expect(vector.preimage).toBeTypeOf('string');
      expect(vector.preimageSha256).toMatch(/^[a-f0-9]{64}$/);
      expect(vector.normalization).toBeTypeOf('object');
      expect(vector.provenance?.generatedBy).toBeTypeOf('string');
      expect(vector.provenance?.verifiedAgainst).toBeTypeOf('string');
      expect(
        digestHasValidShape(vector),
        `${file}: expectedHash is a valid ${vector.hashAlgorithm}/${vector.hashEncoding} digest`,
      ).toBe(true);
    });

    it(`${file}: reconstructs its preimage from canonicalPayload + fieldOrder`, () => {
      expect(buildPreimage(vector.canonicalPayload, vector.fieldOrder)).toBe(vector.preimage);
      expect(sha256Hex(vector.preimage)).toBe(vector.preimageSha256);
    });

    it(`${file}: sanitized — no key material, no credential-shaped strings, fake ids only`, () => {
      expect(text.includes(GOLDEN_TEST_API_KEY), 'fixture must carry the key alias, not the key value').toBe(false);
      const ambientKey = process.env.PAYWAY_API_KEY;
      if (ambientKey) {
        expect(text.includes(ambientKey), 'fixture must never embed an ambient API key').toBe(false);
      }
      for (const { name, pattern } of CREDENTIAL_PATTERNS) {
        expect(pattern.test(text), `${file}: ${name} found in fixture`).toBe(false);
      }
      // Sanitized ids: merchant/partner ids are the fixed test aliases.
      const merchantId = vector.canonicalPayload.merchant_id;
      const partnerId = vector.canonicalPayload.partner_id;
      expect(merchantId === undefined || merchantId === 'TESTMID').toBe(true);
      expect(partnerId === undefined || partnerId === 'TESTPARTNER').toBe(true);
    });

    it(`${file}: fieldOrder matches a HASH_ORDER_HINTS composition (ties the vector to the live call site)`, () => {
      expect(Object.values(HASH_ORDER_HINTS)).toContain(vector.fieldOrder.join('.'));
    });
  }
});

// ── 2. Golden recompute ─────────────────────────────────────────────────────

describe('golden vectors reproduce the pinned hashes through generateHmac', () => {
  for (const { file, vector } of vectors) {
    it(`${file}: ${vector.operation}`, () => {
      const evaluation = evaluateVector(vector, GOLDEN_TEST_API_KEY);
      if (!evaluation.ok) {
        const failure = evaluation.failure;
        // The API key is never printed — compare preimage hashes, not secrets.
        throw new Error(
          [
            `Golden vector ${vector.vectorId} (${vector.operation}) FAILED to reproduce.`,
            '',
            'The signing/canonicalization output for this operation has changed since the fixture was pinned.',
            '',
            'If this change was INTENTIONAL:',
            '  1. regenerate with: npx tsx scripts/generate/gen-golden-vectors.ts',
            '  2. review the fixtures/vectors/hmac/ diff (append-only policy — record the reason in the commit),',
            '  3. commit the fixtures and the signing change TOGETHER.',
            '',
            'If it was NOT intentional, you broke canonicalization — investigate before shipping.',
            '',
            `failure kind: ${failure?.kind}`,
            failure?.firstDifferingField
              ? `first differing preimage field: "${failure.firstDifferingField.field}" (offset ${failure.firstDifferingField.position})`
              : undefined,
            `expected preimage sha256: ${failure?.expectedPreimageSha256}`,
            `actual   preimage sha256: ${failure?.actualPreimageSha256}`,
            failure?.detail,
          ]
            .filter((line) => line !== undefined)
            .join('\n'),
        );
      }
      expect(evaluation.ok).toBe(true);
    });
  }
});

// ── 3. Bidirectional family pinning (dynamic export resolution) ─────────────

describe('vectors naming a *_HASH_FIELDS export pin exactly that export', () => {
  const families = collectHashFieldFamilyExports();

  it('the dynamic scan finds the expected hash-field family exports', () => {
    // Sanity floor for the scan itself (not the family list — that is dynamic).
    expect(Object.keys(families).length).toBeGreaterThanOrEqual(6);
  });

  for (const { file, vector } of vectors) {
    if (vector.hashFieldsFamily.startsWith('inline:')) continue;
    it(`${file}: fieldOrder === ${vector.hashFieldsFamily}`, () => {
      const family = families[vector.hashFieldsFamily];
      expect(
        family,
        `export ${vector.hashFieldsFamily} no longer exists — the vector needs regenerating or re-homing`,
      ).toBeDefined();
      expect(vector.fieldOrder).toEqual([...family]);
    });
  }

  it('every family export agrees with its HASH_ORDER_HINTS entry (drift-guard handshake)', () => {
    const hintValues = new Set(Object.values(HASH_ORDER_HINTS));
    for (const [name, fields] of Object.entries(families)) {
      expect(hintValues.has(fields.join('.')), `family ${name} is not referenced by any HASH_ORDER_HINTS entry`).toBe(
        true,
      );
    }
  });
});

// ── 4. Coverage gate ────────────────────────────────────────────────────────

describe('coverage gate: every hash-field family is pinned by at least one vector', () => {
  it('every *_HASH_FIELDS / *_HMAC_FIELDS export has a pinning vector', () => {
    const families = collectHashFieldFamilyExports();
    const uncovered = computeUncoveredFamilies(
      families,
      vectors.map((v) => ({ hashFieldsFamily: v.vector.hashFieldsFamily })),
    );
    expect(
      uncovered,
      'uncovered hash-field family exports — add a vector in scripts/generate/gen-golden-vectors.ts and regenerate the fixtures',
    ).toEqual([]);
  });

  it('every HASH_ORDER_HINTS composition (inline families included) has a pinning vector', () => {
    const uncovered = computeUncoveredHints(
      HASH_ORDER_HINTS,
      vectors.map((v) => ({ fieldOrder: v.vector.fieldOrder })),
    );
    expect(uncovered, 'endpoints whose signed composition is pinned by no golden vector').toEqual([]);
  });

  it('every inline:<endpoint> family name is a real endpoint with the matching live composition', () => {
    expect(
      inlineFamilyMismatches(
        vectors.map((v) => ({ hashFieldsFamily: v.vector.hashFieldsFamily, fieldOrder: v.vector.fieldOrder })),
        HASH_ORDER_HINTS,
        ENDPOINTS,
      ),
    ).toEqual([]);
  });

  it('negative control: the coverage logic flags a synthetic uncovered family', () => {
    const syntheticFamilies = {
      ...collectHashFieldFamilyExports(),
      SYNTHETIC_UNCOVERED_HASH_FIELDS: ['field_a', 'field_b'],
    };
    const pins = vectors.map((v) => ({ hashFieldsFamily: v.vector.hashFieldsFamily }));
    const uncovered = computeUncoveredFamilies(syntheticFamilies, pins);
    expect(uncovered).toContain('SYNTHETIC_UNCOVERED_HASH_FIELDS');
    // ...and only that one (all real families are covered by the earlier test).
    expect(uncovered).toEqual(['SYNTHETIC_UNCOVERED_HASH_FIELDS']);
  });

  it('negative control: coverage logic passes once the synthetic family gains a pin', () => {
    const pins = [
      ...vectors.map((v) => ({ hashFieldsFamily: v.vector.hashFieldsFamily })),
      { hashFieldsFamily: 'SYNTHETIC_UNCOVERED_HASH_FIELDS' },
    ];
    expect(computeUncoveredFamilies({ SYNTHETIC_UNCOVERED_HASH_FIELDS: ['field_a'] }, pins)).toEqual([]);
  });

  it('negative control: the hint-coverage logic flags a synthetic uncovered endpoint', () => {
    const syntheticHints = { ...HASH_ORDER_HINTS, syntheticEndpoint: 'partner_id.field_a.field_b' };
    const uncovered = computeUncoveredHints(
      syntheticHints,
      vectors.map((v) => ({ fieldOrder: v.vector.fieldOrder })),
    );
    expect(uncovered).toContain('syntheticEndpoint');
  });

  it('negative control: inline-family handshake flags a synthetic composition drift', () => {
    // Simulate the real regression shape: the payout composition changed in
    // code AND in its hint, but the fixture still pins the old order.
    const driftedHints = {
      ...HASH_ORDER_HINTS,
      [ENDPOINTS.payout]: 'merchant_id.tran_id.amount.beneficiaries.custom_fields.currency',
    };
    const mismatches = inlineFamilyMismatches(
      vectors.map((v) => ({ hashFieldsFamily: v.vector.hashFieldsFamily, fieldOrder: v.vector.fieldOrder })),
      driftedHints,
      ENDPOINTS,
    );
    expect(mismatches).toEqual([{ family: 'inline:payout', reason: 'hint_mismatch' }]);
  });
});

// ── 5. Payout regression controls (synthetic + one live-code capture) ───────

describe('payout regression controls: the machinery catches reorder + encoding regressions', () => {
  const payoutVector = vectorById.get('hmac-payout-001');

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('the real payout vector is the hex-encoded pin (PO-003 anchor)', () => {
    expect(payoutVector).toBeDefined();
    expect(payoutVector?.hashEncoding).toBe('hex');
    expect(evaluateVector(payoutVector!, GOLDEN_TEST_API_KEY).ok).toBe(true);
  });

  it('LIVE CODE: the payout domain still hands request() a hex encoding and the pinned field order', async () => {
    // The vector recompute is fixture-driven; THIS is the live-code tie: the
    // domain must keep passing hashEncoding 'hex' (position 6 of request()).
    const captured: Array<{ path: string; hmacFields: string[]; hashEncoding?: string }> = [];
    const spy = async <T>(
      path: string,
      _body: Record<string, unknown>,
      hmacFields: string[],
      _timeFieldName?: 'req_time' | 'request_time',
      _contentType?: string,
      hashEncoding?: 'base64' | 'hex',
    ): Promise<T> => {
      captured.push({ path, hmacFields, hashEncoding });
      return { status: { code: '00' } } as T;
    };
    vi.spyOn(console, 'warn').mockImplementation(() => {});
    const domain = createPayoutDomain(
      {
        merchantId: 'TESTMID',
        apiKey: GOLDEN_TEST_API_KEY,
        environment: 'sandbox',
        // PKCS1 output is randomized — irrelevant here: the spy swallows the
        // encrypted blob before anything is pinned; the key only has to be
        // structurally valid for the domain's pre-flight checks.
        publicKeyPem: generateTestRsaKeyPair().publicKey,
      } as PayWayConfig & { merchantId: string; apiKey: string },
      spy,
      async <T>(path: string): Promise<T> => {
        captured.push({ path, hmacFields: [], hashEncoding: undefined });
        return { status: { code: '00' } } as T;
      },
    );
    await domain.payout({
      transactionId: 'GV-TXN-PO-LIVE',
      amount: 5,
      currency: 'USD',
      beneficiaries: [{ account: '500000001', amount: 5 }],
    });
    expect(captured).toHaveLength(1);
    expect(captured[0].hashEncoding).toBe('hex');
    expect(captured[0].hmacFields.join('.')).toBe(payoutVector!.fieldOrder.join('.'));
  });

  it('synthetic: swapping two payout hash fields is caught (payout hex regression)', () => {
    // Simulate a regression that reorders the payout composition (beneficiaries
    // and amount transposed): the SAME pinned digest, recomputed against the
    // SWAPPED order, must fail the machinery.
    const swapped = [...payoutVector!.fieldOrder];
    const beneficiariesAt = swapped.indexOf('beneficiaries');
    const amountAt = swapped.indexOf('amount');
    swapped[beneficiariesAt] = 'amount';
    swapped[amountAt] = 'beneficiaries';

    const regressed: GoldenVector = { ...payoutVector!, fieldOrder: swapped };
    expect(regressed.fieldOrder.join('.')).toBe('merchant_id.tran_id.amount.beneficiaries.custom_fields.currency');
    // A hash honestly recomputed under the regressed order differs from the
    // pinned digest (order-sensitivity of the pin)...
    const regressedHash = generateHmac(
      regressed.canonicalPayload,
      regressed.fieldOrder,
      GOLDEN_TEST_API_KEY,
      regressed.hashEncoding,
      regressed.hashAlgorithm,
    );
    expect(regressedHash).not.toBe(payoutVector!.expectedHash);
    // ...and the vector machinery reports the mismatch (what CI would see).
    const evaluation = evaluateVector({ ...regressed, expectedHash: regressedHash }, GOLDEN_TEST_API_KEY);
    expect(evaluation.ok).toBe(false);
    expect(evaluation.failure?.kind).toBe('preimage_mismatch');
    expect(evaluation.failure?.firstDifferingField?.field).toBeDefined();
    // The pinned world (original order, original digest) still passes — the
    // failure above comes ONLY from the reordering, not fixture damage.
    expect(evaluateVector(payoutVector!, GOLDEN_TEST_API_KEY).ok).toBe(true);
  });

  it('synthetic: a hex->base64 encoding regression on payout is caught (PO-003)', () => {
    // A regression that flips the payout hash to the SDK-wide base64 default:
    // the base64 digest genuinely differs from the pinned hex digest...
    const base64Digest = generateHmac(
      payoutVector!.canonicalPayload,
      payoutVector!.fieldOrder,
      GOLDEN_TEST_API_KEY,
      'base64',
      'sha512',
    );
    expect(base64Digest).not.toBe(payoutVector!.expectedHash);
    // ...and the machinery flags the mutated clone (wrong digest shape AND
    // wrong value) instead of silently accepting it.
    const evaluation = evaluateVector({ ...payoutVector!, hashEncoding: 'base64' }, GOLDEN_TEST_API_KEY);
    expect(evaluation.ok).toBe(false);
    expect(evaluation.failure?.kind).toBe('digest_shape');
  });
});

describe('N-11: generateHmac rejects objects/arrays in hashed positions', () => {
  it('throws PayWayConfigError naming the field instead of hashing "[object Object]"', () => {
    // The former hmac-purchase-006 vector pinned the silent '[object Object]'
    // coercion; the N-11 fix (2026-10-06) made that a hard throw. The QR
    // return_params passthrough this guard exposed is fixed in qr.ts.
    const payload = { req_time: '20260101120000', items: { raw: 'object' } };
    expect(() => generateHmac(payload, ['req_time', 'items'], GOLDEN_TEST_API_KEY)).toThrow(PayWayConfigError);
    expect(() => generateHmac(payload, ['req_time', 'items'], GOLDEN_TEST_API_KEY)).toThrow(/"items"/);
  });

  it('arrays throw; booleans/numbers keep the pinned coercion (hmac-purchase-005)', () => {
    expect(() => generateHmac({ payout: [{ account: '1' }] }, ['payout'], GOLDEN_TEST_API_KEY)).toThrow(
      PayWayConfigError,
    );
    expect(generateHmac({ skip_success_page: true }, ['skip_success_page'], GOLDEN_TEST_API_KEY)).toBe(
      generateHmac({ skip_success_page: 'true' }, ['skip_success_page'], GOLDEN_TEST_API_KEY),
    );
    expect(generateHmac({ amount: 5 }, ['amount'], GOLDEN_TEST_API_KEY)).toBe(
      generateHmac({ amount: '5' }, ['amount'], GOLDEN_TEST_API_KEY),
    );
  });
});
