import { execFileSync, spawnSync } from 'node:child_process';
import { copyFileSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const numbered = /^\d{2,}-.*\.md$/;
const generated = /<!--\s*(?:GENERATED STUB:|Mirrored from docs\/guides\/)/;

function withFixture(run: (dir: string, script: string) => void): void {
  const dir = mkdtempSync(path.join(tmpdir(), 'payway-guide-stubs-'));
  for (const folder of ['scripts', 'docs/guides']) mkdirSync(path.join(dir, folder), { recursive: true });
  const script = path.join(dir, 'scripts/generate-guide-stubs.mjs');
  copyFileSync(path.join(root, 'scripts/generate-guide-stubs.mjs'), script);
  try { run(dir, script); } finally { rmSync(dir, { recursive: true, force: true }); }
}

describe('canonical guides and compatibility mirrors', () => {
  it('keeps every numbered compatibility copy equal to its canonical guide', () => {
    const copies = readdirSync(path.join(root, 'docs')).filter(name => numbered.test(name));
    expect(copies.length).toBeGreaterThan(0);
    for (const name of copies) {
      const body = readFileSync(path.join(root, 'docs/guides', name), 'utf8');
      const copy = readFileSync(path.join(root, 'docs', name), 'utf8');
      expect(copy, name).toBe(`<!-- Mirrored from docs/guides/${name} — edits belong there; regenerated by scripts/generate-guide-stubs.mjs -->\n\n${body}`);
      expect(copy.split('\n').filter(line => generated.test(line)), name).toHaveLength(1);
    }
  });

  it('rejects generated compatibility headers in canonical guides', () => {
    for (const name of readdirSync(path.join(root, 'docs/guides')).filter(name => name.endsWith('.md'))) {
      expect(readFileSync(path.join(root, 'docs/guides', name), 'utf8'), name).not.toMatch(generated);
    }
  });

  it('repairs a stale nested header and is idempotent afterward', () => withFixture((dir, script) => {
    const name = '01-guide.md';
    const copy = path.join(dir, 'docs', name);
    writeFileSync(path.join(dir, 'docs/guides', name), '# Canonical guide\n');
    writeFileSync(copy, '<!-- GENERATED STUB: stale -->\n\n<!-- GENERATED STUB: stale -->\nWrong body\n');
    expect(execFileSync(process.execPath, [script], { encoding: 'utf8' })).toContain('rewrote 1');
    const repaired = readFileSync(copy, 'utf8');
    expect(repaired).toContain('\n\n# Canonical guide\n');
    expect(repaired.split('\n').filter(line => generated.test(line))).toHaveLength(1);
    expect(execFileSync(process.execPath, [script], { encoding: 'utf8' })).toContain('rewrote 0');
    expect(readFileSync(copy, 'utf8')).toBe(repaired);
  }));

  it('fails on an orphan without rewriting the preserved file', () => withFixture((dir, script) => {
    const copy = path.join(dir, 'docs/01-orphan.md');
    writeFileSync(copy, 'Preserved evidence\n');
    const result = spawnSync(process.execPath, [script], { encoding: 'utf8' });
    expect(result.status).toBe(1);
    expect(result.stderr).toContain('01-orphan.md');
    expect(readFileSync(copy, 'utf8')).toBe('Preserved evidence\n');
  }));

  it('lists intentional unmirrored guides without creating compatibility files', () => withFixture((dir, script) => {
    writeFileSync(path.join(dir, 'docs/guides/23-close-transaction.md'), '# Canonical guide\n');
    const output = execFileSync(process.execPath, [script], { encoding: 'utf8' });
    expect(output).toContain('23-close-transaction.md');
    expect(output).toContain('by design');
    expect(readdirSync(path.join(dir, 'docs'))).toEqual(['guides']);
  }));
});
