/**
 * Knowledge-corpus freshness gate: `knowledge/` + `llms.txt` are GENERATED by
 * `npm run sync:knowledge` (scripts/sync-knowledge.mjs) from the curated
 * sources in scripts/knowledge-sources.mjs. These tests fail when a source
 * doc changed without a re-sync, or when a generated file was hand-edited —
 * the mechanical answer to the audit's #1 recurring finding (surface drift).
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const knowledgeDir = path.join(repoRoot, 'knowledge');

interface KnowledgeTopic {
  topic: string;
  title: string;
  description: string;
  source: string;
  file: string;
  bytes: number;
  /** sha256[:16] of the transformed corpus copy — the hand-edit detector. */
  sha256: string;
  /** sha256[:16] of the raw source doc — the staleness detector. */
  sourceSha256: string;
}
interface KnowledgeManifest {
  schema: string;
  generator: string;
  topics: KnowledgeTopic[];
}

const manifest: KnowledgeManifest = JSON.parse(
  readFileSync(path.join(knowledgeDir, 'MANIFEST.json'), 'utf8'),
) as KnowledgeManifest;

const sha16 = (buf: Buffer | string) => createHash('sha256').update(buf).digest('hex').slice(0, 16);

describe('knowledge corpus freshness', () => {
  it('has a v1 manifest with topics', () => {
    expect(manifest.schema).toBe('knowledge-manifest/v1');
    expect(manifest.topics.length).toBeGreaterThanOrEqual(29);
  });

  it('keeps sources current — every source doc hash matches the manifest', () => {
    const stale = manifest.topics.filter((t) => {
      const sourcePath = path.join(repoRoot, t.source);
      if (!existsSync(sourcePath)) return true;
      return sha16(readFileSync(sourcePath)) !== t.sourceSha256;
    });
    expect(
      stale.map((t) => t.source),
      `stale corpus — run \`npm run sync:knowledge\` for: ${stale.map((t) => t.source).join(', ')}`,
    ).toEqual([]);
  });

  it('keeps generated files pristine — every corpus copy matches its manifest hash', () => {
    const drifted = manifest.topics.filter((t) => {
      const file = path.join(knowledgeDir, t.file);
      if (!existsSync(file)) return true;
      return sha16(readFileSync(file)) !== t.sha256;
    });
    expect(drifted.map((t) => t.file)).toEqual([]);
  });

  it('keeps the critical integration topics in the corpus', () => {
    const topics = new Set(manifest.topics.map((t) => t.topic));
    for (const critical of [
      'quickstart',
      'setup',
      'web-implementation',
      'callbacks-webhooks',
      'errors-and-debugging',
      'payment-link',
      'sdk-cli-reference',
      'error-codes',
      'agent-setup-playbook',
    ]) {
      expect(topics.has(critical), `missing critical topic: ${critical}`).toBe(true);
    }
  });

  it('never ships internal audit dossiers', () => {
    const files = manifest.topics.map((t) => t.file.toLowerCase());
    for (const forbidden of [
      'sandbox-findings',
      'integration-gaps',
      'project-status',
      'competitive',
      'close-transaction-findings',
    ]) {
      expect(files.some((f) => f.includes(forbidden))).toBe(false);
    }
  });

  it('sources every topic from a public directory — no internal provenance (D01/R03)', () => {
    // Mirrors the generator-side gate in scripts/sync-knowledge.mjs: this test
    // fails on an intentionally introduced internal source BEFORE packaging.
    const publicSource = /^(?:[^/]+\.(?:md|json)$|docs\/README\.md$|docs\/guides\/|docs\/recipes\/|docs\/reference\/|docs\/error-codes\.json$)/;
    const offenders = manifest.topics
      .filter((t) => !publicSource.test(t.source.replaceAll('\\', '/')))
      .map((t) => `${t.topic} -> ${t.source}`);
    expect(offenders).toEqual([]);
  });

  it('generates llms.txt listing every topic', () => {
    const llms = readFileSync(path.join(repoRoot, 'llms.txt'), 'utf8');
    expect(llms.startsWith('# aba-payway-ts')).toBe(true);
    for (const topic of manifest.topics) {
      expect(llms).toContain(`](${topic.source})`);
    }
  });

  it('leaves no forbidden package strings in generated files', () => {
    for (const topic of manifest.topics) {
      const content = readFileSync(path.join(knowledgeDir, topic.file), 'utf8');
      expect(content).not.toMatch(/SANDBOX-FINDINGS\.md/i);
      expect(content).not.toMatch(/HANDOFF\.md/i);
      expect(content).not.toMatch(/CLOSE-TRANSACTION-FINDINGS/i);
    }
  });
});
