import {execFileSync} from 'node:child_process';
import {mkdirSync, writeFileSync, readdirSync, readFileSync, existsSync} from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const dest=path.join(root,'.scratch/publishing-dx-audit-2026-09-29/consumer');
mkdirSync(dest,{recursive:true});
const npmCli=path.join(path.dirname(process.execPath),'node_modules/npm/bin/npm-cli.js');
const env=Object.fromEntries(Object.entries(process.env).filter(([k])=>!k.startsWith('PAYWAY_')&&k!=='NODE_OPTIONS'));
Object.assign(env,{APPDATA:dest,PAYWAY_DATA_DIR:path.join(dest,'data'),PAYWAY_NO_UPDATE_CHECK:'1'});
const npm=(args,cwd)=>execFileSync(process.execPath,[npmCli,...args],{cwd,env,encoding:'utf8',stdio:['ignore','pipe','pipe']});
const parsed=JSON.parse(npm(['pack','--json','--ignore-scripts','--pack-destination',dest],root));
const pack=Array.isArray(parsed)?parsed[0]:Object.values(parsed)[0];
writeFileSync(path.join(dest,'package.json'),JSON.stringify({private:true,type:'module'}));
npm(['install',path.join(dest,pack.filename),'--ignore-scripts','--no-audit','--no-fund'],dest);
const installed=path.join(dest,'node_modules/aba-payway-ts');
const run=(args)=>execFileSync(process.execPath,args,{cwd:dest,env,encoding:'utf8',stdio:['ignore','pipe','pipe']});
writeFileSync(path.join(dest,'probe.mjs'),"import {PayWay,server} from 'aba-payway-ts'; if(!PayWay||!server)throw Error('Missing ESM');");
writeFileSync(path.join(dest,'probe.cjs'),"const {PayWay,server}=require('aba-payway-ts'); if(!PayWay||!server)throw Error('Missing CJS');");
run(['probe.mjs']);run(['probe.cjs']);
writeFileSync(path.join(dest,'probe.ts'),"import type {PayWayConfig,TransactionSession} from 'aba-payway-ts';const c:PayWayConfig={merchantId:'fixture',apiKey:'fixture'};const s:TransactionSession|undefined=undefined;void c;void s;");
run([path.join(root,'node_modules/typescript/bin/tsc'),'--noEmit','--strict','--target','ES2022','--module','NodeNext','--moduleResolution','NodeNext','--skipLibCheck','probe.ts']);
const cli=path.join(installed,'dist/cli.js');
const help=run([cli,'--help']);const demo=run([cli,'demo','--check']);
const catalog=JSON.parse(run([cli,'mcp','--list-tools','--json']));
const docs=run([cli,'docs','list']);
const skillsDir=path.join(dest,'installed-skills');
run([cli,'skills','add','codex','--dest',skillsDir]);
const doctor=run([cli,'skills','doctor','--agent','codex','--dest',skillsDir]);
const count=readdirSync(path.join(installed,'skills'),{withFileTypes:true}).filter(e=>e.isDirectory()&&e.name.startsWith('aba-payway-')).length;
const evidence={node:process.version,packFiles:pack.files.length,packedBytes:pack.size,unpackedBytes:pack.unpackedSize,esm:true,cjs:true,types:true,cliHelp:help.includes('payway-sdk'),demo:demo.includes('Credential-free demo check passed'),skills:count,skillsDoctor:doctor,docsListContainsQuickstart:docs.includes('quickstart'),mcpCatalog:catalog,internalDossierPackaged:existsSync(path.join(installed,'knowledge/close-transaction-findings.md')),missingLlmsTargets:[]};
for(const m of readFileSync(path.join(installed,'llms.txt'),'utf8').matchAll(/\]\(([^)]+)\)/g))if(!/^[a-z]+:/i.test(m[1])&&!existsSync(path.join(installed,m[1])))evidence.missingLlmsTargets.push(m[1]);
writeFileSync(path.join(root,'.scratch/publishing-dx-audit-2026-09-29/consumer-evidence.json'),JSON.stringify(evidence,null,2));
console.log(JSON.stringify({...evidence,skillsDoctor:'exit 0',mcpCatalog:'parsed successfully',missingLlmsTargets:evidence.missingLlmsTargets.length},null,2));
