import type { TemplateFile } from '../../../config/templates/types.js';

const starter = `// First sandbox payment — generated by \`payway-sdk init\`.
//
// Environment strategy (audit S01): this script reads process.env directly
// and does NOT parse .env itself. Run it with the command printed by init —
// \`node --env-file-if-exists=.env payway-first-payment.mjs\` — or export the
// PAYWAY_* variables another way. Precedence: real environment variables
// win over .env values (Node loads --env-file without overriding them).
// Keep credentials on the server; never ship them to a browser or chat.
import { PayWay, PayWayNetworkError, paymentNextStep } from 'aba-payway-ts';

const callbackUrl = process.env.PAYWAY_CALLBACK_URL;
if (!callbackUrl) {
  throw new Error('Set PAYWAY_CALLBACK_URL to a public HTTPS endpoint before creating an online QR.');
}

const transactionId = \`pay-\${Date.now().toString(36)}\`;
const payway = new PayWay();

try {
  const created = await payway.qr.generateQr({
    transactionId,
    amount: 3,
    currency: 'USD',
    callbackUrl,
    lifetime: 300,
  });

  console.log(JSON.stringify({
    transactionId,
    creation: 'accepted',
    lifecycle: 'created',
    guidance: paymentNextStep('created'),
    qrString: created.qrString,
    next: \`payway-sdk check-transaction -t \${transactionId}\`,
  }, null, 2));
} catch (error) {
  if (error instanceof PayWayNetworkError) {
    console.error(\`The create outcome is unknown. Check \${transactionId} before creating another payment.\`);
  }
  throw error;
}
`;

export const FIRST_PAYMENT_TEMPLATE: readonly TemplateFile[] = [{ path: 'payway-first-payment.mjs', content: starter }];
