/**
 * .env.example renderer (audit P1-05 — DX-KNOW-005b).
 *
 * Renders the complete, grouped, commented environment-variable reference
 * from the generated registry (src/generated/env-registry.ts, itself emitted
 * from knowledge/rules/env-vars.yaml). Two consumers share this ONE
 * implementation — they are different jobs (audit P1-05: "init writes two
 * distinct artifacts ... They are different jobs and must not be the same
 * string constant") and must never drift:
 *
 *   - scripts/generate/gen-env-vars.ts writes the text to the repo root
 *     (.env.example, regenerated by `npm run gen:env-vars`, drift-gated by
 *     `-- --check`);
 *   - src/cli/commands/init.ts writes the identical text into NEW projects.
 *
 * Formatting rules that keep the output parseable by src/cli/dotenv.ts:
 *   - comments always sit on their OWN lines (the loader has no inline
 *     comment support — a trailing `# ...` would become part of the value);
 *   - the RSA PUBLIC-key block demonstrates both supported PEM syntaxes
 *     (single line with literal \n escapes, and a quoted multi-line value);
 *   - secret variables are empty placeholders — a real value must never be
 *     committed here.
 */
import type { PayWayEnvVarDefinition, PayWayEnvVarGroup } from '../generated/env-registry.js';

/** Section order in .env.example. Kept in sync with the registry's group union (conformance-tested). */
export const ENV_EXAMPLE_GROUP_ORDER: readonly PayWayEnvVarGroup[] = [
  'connection',
  'credentials',
  'urls',
  'tls',
  'behavior',
  'data',
  'integrations',
];

const ENV_EXAMPLE_GROUP_TITLES: Record<PayWayEnvVarGroup, string> = {
  connection: 'Connection',
  credentials: 'Credentials',
  urls: 'URLs (return / cancel / callback)',
  tls: 'TLS (certificate verification)',
  behavior: 'Behavior toggles',
  data: 'Data directories (local stores)',
  integrations: 'Integrations (agent REPL, KHQR)',
};

const COMMENT_WRAP_WIDTH = 96;

const PEM_SINGLE_LINE_SAMPLE =
  '"-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\\n-----END PUBLIC KEY-----"';
const PEM_BODY_SAMPLE = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Z8QhXrSAMPLE-KEY-BODY';

/** Greedy word wrap, deterministic (same input, same lines). */
function wrapComment(text: string): string[] {
  const words = text.split(/\s+/).filter((word) => word !== '');
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    const candidate = current === '' ? word : `${current} ${word}`;
    if (candidate.length > COMMENT_WRAP_WIDTH && current !== '') {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current !== '') lines.push(current);
  return lines;
}

function renderVarBlock(envVar: PayWayEnvVarDefinition): string[] {
  const lines: string[] = [];
  const description = `${envVar.name} — ${(envVar.required ? 'REQUIRED. ' : '') + envVar.description}`;
  lines.push(...wrapComment(description).map((line) => `# ${line}`));
  lines.push(`#   Kind: ${envVar.kind}${envVar.required ? ' (required)' : ''}`);
  lines.push(`#   Default: ${envVar.defaultValue ?? 'unset (built-in default applies)'}`);
  if (envVar.kind === 'secret') {
    lines.push('#   NEVER COMMIT A REAL VALUE — replace the placeholder below out-of-band.');
  }
  if (envVar.pemSyntax) {
    lines.push('#   The CLI .env loader accepts both forms (the quotes make it fold \\n escapes):');
    lines.push(`#     single-line (quoted, literal \\n escapes): ${envVar.name}=${PEM_SINGLE_LINE_SAMPLE}`);
    lines.push('#     multi-line (quoted):');
    lines.push(`#       ${envVar.name}="-----BEGIN PUBLIC KEY-----`);
    lines.push(`#       ${PEM_BODY_SAMPLE}`);
    lines.push('#       -----END PUBLIC KEY-----"');
  } else if (envVar.example !== undefined) {
    lines.push(`#   Example: ${envVar.name}=${envVar.example}`);
  }
  const isPlaceholder = envVar.kind === 'secret' || envVar.defaultValue === null;
  lines.push(`${envVar.name}=${isPlaceholder ? '' : envVar.defaultValue}`);
  return lines;
}

/**
 * Render the complete .env.example text. Pure function of the registry —
 * same registry, same bytes (conformance test asserts the committed root
 * .env.example matches exactly).
 */
export function buildEnvExampleText(vars: readonly PayWayEnvVarDefinition[]): string {
  const lines: string[] = [
    '# ABA PayWay SDK — complete environment-variable reference (GENERATED).',
    '#',
    '# Emitted deterministically by scripts/generate/gen-env-vars.ts from',
    '# knowledge/rules/env-vars.yaml. Regenerate with `npm run gen:env-vars` —',
    '# do not edit by hand.',
    '#',
    '# Copy to `.env` and fill in the values you need. `.env` holds real',
    '# credentials and is git-ignored; THIS file is the only env file that',
    '# should ever be committed.',
    '#',
    '# Secret variables below are placeholders — NEVER commit real values.',
  ];
  for (const group of ENV_EXAMPLE_GROUP_ORDER) {
    const groupVars = vars.filter((envVar) => envVar.group === group);
    if (groupVars.length === 0) continue;
    lines.push('');
    lines.push('# -------------------------------------------------------------------------');
    lines.push(`# ${ENV_EXAMPLE_GROUP_TITLES[group]}`);
    lines.push('# -------------------------------------------------------------------------');
    for (const envVar of groupVars) {
      lines.push('');
      lines.push(...renderVarBlock(envVar));
    }
  }
  lines.push('');
  return `${lines.join('\n')}\n`;
}
