/**
 * Capture the QR template gallery (docs/images/qr-templates/*.png).
 *
 * Branded QR images are RENDERED BY THE GATEWAY — the offline/local pipeline
 * can only produce plain unbranded QRs — so each sample requires one real
 * sandbox `generate-qr` call. This script loops over every sandbox-verified
 * template (src/constants.ts QR_TEMPLATES), requests a small USD QR, and saves
 * the returned `qrImage` data-URL as a PNG next to this repo's docs.
 *
 * Credentials come from the standard resolution chain: PAYWAY_* env vars, or
 * the profile named by PAYWAY_PROFILE, or the profile store's default profile.
 *
 * Idempotent: existing PNGs are skipped unless `--force` is passed.
 * Run (sandbox TLS: pass PAYWAY_TLS_CA_FILE="$PWD/payway-sandbox-ca.pem" —
 * a locally-extracted CA bundle, gitignored; see scripts/extract-sandbox-ca.mjs):
 *
 *     PAYWAY_TLS_CA_FILE="$PWD/payway-sandbox-ca.pem" npx tsx scripts/capture-qr-template-gallery.ts
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { PayWay } from '../src/index.js';
import { QR_TEMPLATE_NAMES } from '../src/constants.js';
import {
  activateProfile,
  activeProfile,
  getProfileByName,
  loadProfileStore,
} from '../src/config/profiles.js';

const force = process.argv.includes('--force');
const outDir = fileURLToPath(new URL('../docs/images/qr-templates/', import.meta.url));
const manifestPath = join(outDir, 'README.md');

const store = loadProfileStore();
const profile =
  (process.env.PAYWAY_PROFILE ? getProfileByName(store, process.env.PAYWAY_PROFILE) : undefined) ??
  activeProfile(store);
if (!profile) {
  console.error('No PayWay profile found. Run `payway-sdk profiles add` or set PAYWAY_PROFILE.');
  process.exit(1);
}
activateProfile(profile);

const payway = new PayWay();

mkdirSync(outDir, { recursive: true });
const manifestLines: string[] = [
  '# QR Template Gallery — capture manifest',
  '',
  'Generated by `scripts/capture-qr-template-gallery.ts` (sandbox `generate-qr`, branded renders are gateway-side).',
  '',
  '| Template | Sandbox tran_id | Captured (UTC) |',
  '|---|---|---|',
];

for (const template of QR_TEMPLATE_NAMES) {
  const outPath = join(outDir, `${template}.png`);
  if (existsSync(outPath) && !force) {
    console.log(`skip ${template} (exists; --force to recapture)`);
    continue;
  }
  const tranId = `qr${Date.now().toString(36)}${randomBytes(3).toString('hex')}`;
  const response = await payway.qr.generateQr({
    transactionId: tranId,
    amount: 5,
    currency: 'USD',
    paymentOption: 'abapay_khqr',
    callbackUrl: 'https://example.com/payway-callback',
    lifetime: 360,
    qrImageTemplate: template,
  });
  const code = response.status?.code;
  if (code !== undefined && code !== '0' && code !== 0) {
    console.error(`FAIL ${template}: gateway status.code=${code} ${response.status?.message ?? ''} (tran_id ${tranId})`);
    process.exitCode = 1;
    continue;
  }
  const dataUrl = response.qrImage ?? '';
  const base64 = dataUrl.replace(/^data:image\/png;base64,/, '');
  if (!base64) {
    console.error(`FAIL ${template}: response carried no qrImage (tran_id ${tranId})`);
    process.exitCode = 1;
    continue;
  }
  writeFileSync(outPath, Buffer.from(base64, 'base64'));
  manifestLines.push(`| \`${template}\` | \`${tranId}\` | ${new Date().toISOString()} |`);
  console.log(`saved ${template}.png (tran_id ${tranId})`);
}

writeFileSync(manifestPath, `${manifestLines.join('\n')}\n`);
console.log(`manifest written to ${manifestPath}`);
