import { existsSync, readFileSync, unlinkSync, writeFileSync, mkdirSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import { resolvePaywayDataRoot } from '../config/data-root.js';

/**
 * Receiver lifecycle state (audit WP02): version 2 binds the state file to a
 * SPECIFIC receiver INSTANCE — a random instanceId and the control token the
 * `webhook stop` command must present to the receiver's control route.
 * Version 1 stored only a shared PID, which let a reused PID (or another
 * workspace's receiver) be signalled as if it were ours.
 */
export interface WebhookLifecycleState {
  version: 2;
  /** Random identity generated by the owning receiver process. */
  instanceId: string;
  /** Shared secret the control route requires for shutdown (local data-root trust domain). */
  controlToken: string;
  pid: number;
  port: number;
  host: string;
  publicBaseUrl: string | null;
  callbackUrl: string | null;
  previousCallbackUrl: string | null;
  startedAt: string;
}

export function createLifecycleState(
  input: Omit<WebhookLifecycleState, 'version' | 'instanceId' | 'controlToken' | 'startedAt'> & { startedAt?: string },
): WebhookLifecycleState {
  return {
    version: 2,
    instanceId: randomUUID(),
    controlToken: randomUUID().replaceAll('-', '') + randomUUID().replaceAll('-', ''),
    startedAt: input.startedAt ?? new Date().toISOString(),
    ...input,
  };
}

export function lifecyclePath(env: NodeJS.ProcessEnv = process.env): string {
  return path.join(resolvePaywayDataRoot(undefined, env), 'webhook_data', 'receiver.json');
}

export function writeLifecycleState(state: WebhookLifecycleState, env?: NodeJS.ProcessEnv): void {
  const file = lifecyclePath(env);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, `${JSON.stringify(state, null, 2)}\n`, 'utf8');
}

export function readLifecycleState(env?: NodeJS.ProcessEnv): WebhookLifecycleState | null {
  const file = lifecyclePath(env);
  if (!existsSync(file)) return null;
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf8')) as WebhookLifecycleState;
    if (
      parsed.version !== 2 ||
      !Number.isInteger(parsed.pid) ||
      !Number.isInteger(parsed.port) ||
      typeof parsed.instanceId !== 'string' ||
      typeof parsed.controlToken !== 'string'
    ) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}

export function clearLifecycleState(env?: NodeJS.ProcessEnv): void {
  try {
    unlinkSync(lifecyclePath(env));
  } catch {
    /* already absent */
  }
}
