name: PayWay - Production
values:
  - key: baseUrl
    value: 'https://checkout.payway.com.kh'
  - key: merchant_id
    value: REPLACE_WITH_YOUR_PRODUCTION_MERCHANT_ID
  - key: secret_key
    value: REPLACE_WITH_YOUR_PRODUCTION_SECRET_KEY
    type: secret
  - key: rsa_public_key
    value: REPLACE_WITH_YOUR_PRODUCTION_RSA_PUBLIC_KEY_PEM
  - key: ctid
    value: REPLACE_WITH_YOUR_PRODUCTION_CTID
  - key: whitelist_payee
    value: REPLACE_WITH_YOUR_WHITELISTED_BENEFICIARY
