/**
 * `payway-sdk docs` — serve the packaged knowledge corpus (integration guides,
 * sandbox learnings, error-code registry) to humans and agents, offline. The
 * corpus is generated by scripts/sync-knowledge.mjs; this command only reads
 * it (src/knowledge/store.ts).
 *
 * Contract: under --json, stdout is exactly one JSON document; failures emit
 * the uniform {error:{kind,exitCode,…}} envelope.
 */
import type { Command } from 'commander';
import { ansi as c } from '../../agent/ansi.js';
import { listTopics, readTopic, searchKnowledge } from '../../knowledge/store.js';

function knowledgeUnavailableJson(): number {
  console.log(
    JSON.stringify(
      {
        error: {
          kind: 'config_error',
          exitCode: 1,
          type: 'PayWayConfigError',
          message:
            'Knowledge corpus not found. In a repo checkout run `npm run sync:knowledge`; in an installed package reinstall aba-payway-ts (knowledge/ ships in the tarball).',
        },
      },
      null,
      2,
    ),
  );
  return 1;
}

function validationErrorJson(message: string): number {
  console.log(
    JSON.stringify({ error: { kind: 'validation', exitCode: 1, type: 'PayWayConfigError', message } }, null, 2),
  );
  return 1;
}

function printUnavailableHint(): void {
  console.log(`  ${c.red('✗')} Knowledge corpus not found.`);
  console.log(`  ${c.dim('In a repo checkout run:')} ${c.cyan('npm run sync:knowledge')}`);
  console.log(
    `  ${c.dim('In an installed package, reinstall aba-payway-ts — the knowledge/ corpus ships in the tarball.')}`,
  );
}

export function registerDocsCommand(program: Command): void {
  program
    .command('docs')
    .description('Read the built-in PayWay knowledge base (guides, sandbox learnings, error codes) — offline')
    .argument('[target]', 'topic slug (payway-sdk docs quickstart), "list", or "search"')
    .argument('[query...]', 'search terms (used with the "search" target)')
    .option('--json', 'Emit machine-readable JSON (one document on stdout)')
    .action((target: string | undefined, query: string[], opts: { json?: boolean }) => {
      const found = listTopics();
      if (!found) {
        if (opts.json) {
          process.exitCode = knowledgeUnavailableJson();
        } else {
          printUnavailableHint();
          process.exitCode = 1;
        }
        return;
      }
      const { topics } = found;

      const action = target ?? 'list';
      if (action === 'list') {
        if (opts.json) {
          console.log(JSON.stringify({ corpusDir: found.dir, topics }, null, 2));
          return;
        }
        console.log(`\n${c.bold('ABA PayWay knowledge base')} — ${topics.length} topics\n`);
        for (const topic of topics) {
          console.log(`  ${c.cyan(topic.topic.padEnd(26))} ${c.bold(topic.title)}`);
          console.log(`  ${c.dim(' '.repeat(26))} ${topic.description}`);
        }
        console.log();
        console.log(`  ${c.dim('Read one:')} ${c.cyan('payway-sdk docs <topic>')}  ${c.dim('Search:')} ${c.cyan('payway-sdk docs search <terms>')}`);
        console.log();
        return;
      }

      if (action === 'search') {
        const needle = query.join(' ').trim();
        if (!needle) {
          const message = 'docs search requires at least one search term';
          if (opts.json) {
            process.exitCode = validationErrorJson(message);
          } else {
            console.log(`  ${c.red('✗')} ${message}`);
            process.exitCode = 1;
          }
          return;
        }
        const result = searchKnowledge(needle);
        if (!result) {
          if (opts.json) {
            process.exitCode = knowledgeUnavailableJson();
          } else {
            printUnavailableHint();
            process.exitCode = 1;
          }
          return;
        }
        if (opts.json) {
          console.log(JSON.stringify({ query: needle, ...result }, null, 2));
          return;
        }
        console.log(`\n${c.bold('Search')}: "${needle}" — ${result.totalHits} hits${result.truncated ? c.dim(' (showing first 40)') : ''}\n`);
        for (const hit of result.hits) {
          console.log(`  ${c.cyan(`${hit.topic}:${hit.line}`)}  ${hit.text}`);
        }
        if (result.hits.length === 0) console.log(`  ${c.dim('No hits. Try shorter terms — e.g.')} ${c.cyan('payway-sdk docs search lifetime')}`);
        console.log();
        return;
      }

      const read = readTopic(action);
      if (!read || read.status === 'missing') {
        const message = `Unknown knowledge topic "${action}". Run payway-sdk docs list for available topics.`;
        if (opts.json) {
          process.exitCode = validationErrorJson(message);
        } else {
          console.log(`  ${c.red('✗')} ${message}`);
          process.exitCode = 1;
        }
        return;
      }
      if (read.status === 'ambiguous') {
        const message = `"${action}" matches several topics: ${read.matches.map((t) => t.topic).join(', ')} — be more specific.`;
        if (opts.json) {
          process.exitCode = validationErrorJson(message);
        } else {
          console.log(`  ${c.red('✗')} ${message}`);
          process.exitCode = 1;
        }
        return;
      }
      if (opts.json) {
        console.log(
          JSON.stringify(
            {
              topic: read.topic.topic,
              title: read.topic.title,
              description: read.topic.description,
              source: read.topic.source,
              bytes: read.topic.bytes,
              content: read.content,
            },
            null,
            2,
          ),
        );
        return;
      }
      console.log(
        `${c.dim(`— payway-sdk knowledge · ${read.topic.title} (${read.topic.source}) —`)}\n\n${read.content}`,
      );
    });
}
