openapi: 3.1.0
info:
  title: PayWay KHQR API - Get Transactions
  version: 1.0.0
servers:
  - url: https://payway.com.kh
paths:
  /api/payment-gateway/v1/payments/get-transactions-by-mc-ref:
    post:
      summary: Get transactions
      description: This API allows you to retrieve purchase transactions using merchant_ref number. You can retrieve details for any past transaction and we response only the last 50 transactions.
      x-hmac-fields:
        - req_time
        - merchant_id
        - merchant_ref
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetTransactionsRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTransactionsResponse'
components:
  schemas:
    GetTransactionsRequest:
      type: object
      required:
        - req_time
        - merchant_id
        - merchant_ref
        - hash
      properties:
        req_time:
          type: string
          description: Request date and time in UTC format as YYYYMMDDHHmmss.
          example: "20250213084236"
        merchant_id:
          type: string
          description: A unique merchant ID provided by ABA Bank
          example: "ec000002"
        merchant_ref:
          type: string
          description: Merchant reference number
          example: "17394277693"
        hash:
          type: string
          description: A Base64-encoded HMAC SHA-512 hash
          example: "QskVi2gEctW...j7Td6kEi/KLPvGcK3ZiA=="
    GetTransactionsResponse:
      type: object
      properties:
        status:
          type: integer
          description: Response status code (e.g., 0 for Success, 1 for Wrong hash, 8 for Invalid merchant profile, 11 for Internal server error)
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        transaction_id:
          type: string
        transaction_date:
          type: string
        bank_ref:
          type: string
        apv:
          type: string
        discount_amount:
          type: number
        payment_status:
          type: string
        payment_amount:
          type: number
        payment_currency:
          type: string
        payment_type:
          type: string
        payer_account:
          type: string
        total_amount:
          type: number
        original_amount:
          type: number
        original_currency:
          type: string
        payment_status_code:
          type: integer
        bank_name:
          type: string
        refund_amount:
          type: number
        merchant_ref:
          type: string
