/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// ÔöÇÔöÇÔöÇ Transaction Polling Types ÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇÔöÇ

/** Terminal payment statuses that stop the polling loop. */
export type TerminalPaymentStatus = 'APPROVED' | 'DECLINED' | 'CANCELLED' | 'REFUNDED';

/** Status values that indicate the transaction is still pending. */
export type PendingPaymentStatus = 'PENDING' | 'PRE-AUTH';

/** A single poll result yielded by the async iterator. */
export interface PollTransactionResult {
  /** The transaction ID being polled. */
  transactionId: string;
  /** 1-based poll attempt number. */
  attempt: number;
  /** The raw response from checkTransaction(). */
  response: components['schemas']['CheckTransactionResponse'];
  /** The extracted payment_status string (e.g. 'PENDING', 'APPROVED'). */
  paymentStatus: string;
  /** Whether this is a terminal status ÔÇö polling will stop after this yield. */
  isTerminal: boolean;
  /** Duration of this specific poll HTTP request in milliseconds. */
  durationMs: number;
  /** ISO-8601 timestamp when this poll completed. */
  timestamp: string;
}

/** Configuration options for pollTransactionStatus(). */
export interface PollTransactionOptions {
  /** Poll interval in milliseconds. Default: 5000 (5 seconds). */
  intervalMs?: number;
  /** Maximum polling duration in milliseconds. Default: 600000 (10 minutes). */
  maxDurationMs?: number;
  /** Maximum consecutive poll errors before aborting. Default: 3. */
  maxConsecutiveErrors?: number;
}

export interface paths {
  '/api/payment-gateway/v1/payments/purchase': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a purchase transaction
     * @description Initiates a payment transaction and returns either a hosted checkout page (HTML) or, for abapay_khqr_deeplink, a JSON payload containing the KHQR string and deeplinks. See info.description for the auth model this endpoint depends on.
     */
    post: operations['createPurchase'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-gateway/v1/payments/check-transaction-2': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Check transaction status (transactions younger than 7 days only)
     * @description Rate limit: 600 requests/second. For transactions older than 7 days, use Get Transaction Details instead (not in this skeleton — add before shipping if needed). NOTE: path includes an unverified "-2" suffix — confirm against sandbox; see info.description item 6.
     */
    post: operations['checkTransaction'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-gateway/v1/payments/close-transaction': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Close (cancel) a transaction before payment completes
     * @description Use for flash sales, bookings, or any flow needing to invalidate a transaction before the customer pays. Once closed, any incoming payment is rejected/reversed and no callback fires.
     */
    post: operations['closeTransaction'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-gateway/v1/payments/transaction-detail': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get full details of a past transaction, including operation history
     * @description Unlike check-transaction, this is NOT for real-time status checks during payment processing — it's for retrieving history on any past transaction, including its list of operations (captures, refunds, cancellations). Hard rate limit: 10 requests/minute, and per the docs this "cannot be increased" — do not build a polling pattern against this endpoint; use check-transaction for anything time-sensitive within 7 days.
     */
    post: operations['getTransactionDetail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-gateway/v1/payments/transaction-list-2': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * List transactions for one outlet, filtered and paginated
     * @description Scoped to a SINGLE outlet — there is no "all outlets under this business profile" mode. Date range is capped at 3 days (including today), even reaching arbitrarily far into the past. Rate limit: 50 requests/minute. NOTE: path includes an unverified "-2" suffix, same caveat as check-transaction — see info.description item 6.
     */
    post: operations['getTransactionList'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/merchant-portal/merchant-access/online-transaction/refund': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Issue a full or partial refund
     * @description Only COMPLETED transactions are eligible. Must be requested within 30 days of the original payment. Multiple partial refunds are allowed until the full paid amount is exhausted. ABA PAY refunds are immediate; Card/WeChat/Alipay follow PayWay's settlement agreement timing. Rate limit: 500 requests/second. CREDENTIALS: requires an RSA public key IN ADDITION TO the HMAC api_key — see info.description item 7. This is the only operation in this spec with that requirement.
     */
    post: operations['refundTransaction'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-gateway/v1/exchange-rate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Fetch ABA Bank's current buy/sell exchange rates
     * @description Rates match https://www.ababank.com/en/forex-exchange. This is the only operation with a 2-field hash (no tran_id involved).
     */
    post: operations['getExchangeRate'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-credential/v3/aof/link-account': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Link an ABA account to your platform
     * @description Returns a QR code or ABA Mobile deeplink, enabling users to scan or use the deeplink to launch ABA Mobile and select an account to link. Once linked, PayWay sends account details and token to the merchant via callback_url.
     */
    post: operations['linkAccount'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-credential/v3/cof/link-card': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Link a credit/debit card to your platform
     * @description Securely stores a customer's credit/debit card. Returns a hosted checkout page or token depending on integration type.
     */
    post: operations['linkCard'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-gateway/v3/purchase/payment-credential': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Charge a stored payment token
     * @description Initiates a payment using a previously linked account or card token. Supports both customer-initiated (CITR) and merchant-initiated (MITR) transactions. Use token_flag to specify the context.
     */
    post: operations['cofPayment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-credential/v3/token-management/renew-expired-account-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Renew an existing payment token
     * @description Used to update or refresh existing payment credentials before they expire. Generates a new token while keeping the linked account/card.
     */
    post: operations['renewToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-credential/v3/token-management/get-token-details': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get details of a linked account or card token
     * @description Retrieves the details associated with a stored payment token, including masked account/card information and token status.
     */
    post: operations['getTokenDetails'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-credential/v3/token-management/remove-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Remove a stored payment token
     * @description Deletes the stored account or card token. Once removed, the token can no longer be used for payments or renewals.
     */
    post: operations['removeToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-gateway/v1/payments/generate-qr': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate a dynamic QR code for payment
     * @description Generates a dynamic KHQR code that can be displayed on any screen (POS terminal, kiosk, website) for customers to scan and pay. The QR is unique per transaction and expires after the configured lifetime. Supports ABA PAY and KHQR payment methods.
     */
    post: operations['generateQr'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/merchant-portal/merchant-access/payment-link/create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a payment link
     * @description Generates a shareable payment link that can be sent to customers via SMS, email, chat, or any messaging platform. The link opens PayWay's hosted checkout page. Requires RSA-encrypted merchant_auth. Sandbox-verified: `currency` and `return_url` are REQUIRED inside merchant_auth — the gateway responds PTL04 "Parameter validation required" when either is omitted (undocumented in official docs).
     */
    post: operations['createPaymentLink'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/merchant-portal/merchant-access/payment-link/detail': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get payment link details
     * @description Retrieves the status and details of a previously created payment link. Also uses RSA-encrypted merchant_auth. The `id` is the `data.id` value returned by the create endpoint — NOT the slug in the payment_link URL.
     */
    post: operations['getPaymentLinkDetails'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/merchant-portal/merchant-access/online-transaction/pre-auth-completion': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Complete a pre-authorized transaction (capture funds)
     * @description Captures funds from a pre-authorized transaction. Must be called within the hold period (typically 7 days for cards). Only PRE-AUTH status transactions are eligible.
     */
    post: operations['completePreAuth'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/merchant-portal/merchant-access/online-transaction/pre-auth-cancellation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel a pre-authorized transaction (release hold)
     * @description Releases the hold on funds from a pre-authorized transaction. Only PRE-AUTH status transactions can be cancelled.
     */
    post: operations['cancelPreAuth'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-gateway/v2/direct-payment/merchant/payout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Disburse funds to a beneficiary account
     * @description Transfers funds from the merchant's settlement account to a whitelisted beneficiary ABA account. Beneficiaries must be added to the whitelist and approved before payouts can be made.
     */
    post: operations['payout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/merchant-portal/merchant-access/whitelist-account/update-whitelist-status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Update the status of a beneficiary
     * @description Enables or disables a whitelisted beneficiary account. Disabled beneficiaries cannot receive payouts until re-enabled.
     */
    post: operations['updateBeneficiaryStatus'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/merchant-portal/merchant-access/whitelist-account/add-whitelist-payout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add a beneficiary to the payout whitelist
     * @description Registers a new ABA account as a payout beneficiary. The beneficiary must be approved by ABA Bank before payouts can be directed to it. Up to 10 beneficiaries can be whitelisted.
     */
    post: operations['addBeneficiary'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/payment-gateway/v1/payments/get-transactions-by-mc-ref': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get transactions by merchant reference
     * @description Retrieves purchase transactions using a merchant_ref number. Returns details for any past transaction, limited to the last 50 transactions matching the reference.
     */
    post: operations['getTransactionsByMerchantRef'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export interface webhooks {
  paymentCallback: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * PayWay's return_url callback (server-to-server pushback)
     * @description PayWay POSTs this to the merchant's return_url (or the profile's configured default) after payment completion. Verify X-PAYWAY-HMAC-SHA512 using the SORTED-KEY algorithm described in info.description item 3 — this is NOT the same signing function used for outbound requests. Reject with 401 on mismatch; do not process the notification.
     */
    post: operations['paymentCallback'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export interface components {
  schemas: {
    PurchaseRequest: {
      /**
       * @description UTC request timestamp, format YYYYMMDDHHmmss. Must be freshly generated at signing time.
       * @example 20250213065545
       */
      req_time: string;
      /** @description Merchant key issued by ABA Bank. */
      merchant_id: string;
      /** @description Merchant-generated unique transaction identifier. */
      tran_id: string;
      /** @description Buyer's first name. Must not contain digits/special characters (rejected as error code 16). */
      firstname?: string;
      /** @description Buyer's last name. Same validation as firstname (error code 17). */
      lastname?: string;
      /** @description Buyer's email (validated server-side, error code 19 if invalid). */
      email?: string;
      /** @description Buyer's phone (validated server-side, error code 18 if invalid). */
      phone?: string;
      /**
       * @description "pre-auth" only supports ABA PAY, KHQR, and Card. Using pre-auth with an unsupported payment_option returns error code 22.
       * @default purchase
       * @enum {string}
       */
      type: 'purchase' | 'pre-auth';
      /**
       * @description Omit to let PayWay auto-display all payment options the merchant profile supports. abapay_khqr_deeplink changes the 200 response from HTML to a JSON object (qr_string, abapay_deeplink, checkout_qr_url) — see PurchaseQrResponse.
       * @enum {string}
       */
      payment_option?: 'cards' | 'abapay_khqr' | 'abapay_khqr_deeplink' | 'alipay' | 'wechat' | 'google_pay';
      /** @description Base64-encoded JSON array of {name, quantity, price}. Descriptive only — NOT used for amount validation or calculation; `amount` is the sole source of truth for what's charged. */
      items?: string;
      /**
       * @description Shipping fee, additive to amount at checkout.
       * @default 0
       */
      shipping: number;
      /** @description Purchase amount. Zero is rejected (error 45). KHR currency cannot carry decimals (error 46) and must exceed 100 KHR (error 47). */
      amount: number;
      /**
       * @description Defaults to the currency of the first account on the merchant profile if omitted.
       * @enum {string}
       */
      currency?: 'KHR' | 'USD';
      /** @description Base64-encoded callback URL. Custom return_url values must be pre-whitelisted on the merchant profile (error 6/81) or the request is rejected. */
      return_url?: string;
      /** @description Redirect target when the customer closes/cancels the payment dialog. */
      cancel_url?: string;
      /**
       * @description Overrides the profile-level "skip success page" setting for this request only. 1 = skip, redirecting via continue_success_url.
       * @enum {integer}
       */
      skip_success_page?: 0 | 1;
      /** @description Redirect target after a successful payment (used when skip_success_page=1). */
      continue_success_url?: string;
      /** @description Base64-encoded JSON {ios_scheme, android_scheme}. Mandatory for mobile-app integrations so ABA Mobile can hand control back to the merchant's native app. */
      return_deeplink?: string;
      /** @description Base64-encoded arbitrary JSON merchants want attached to the transaction record/export (not used by PayWay's own logic). */
      custom_fields?: string;
      /** @description Opaque string echoed back verbatim in the return_url pushback payload. */
      return_params?: string;
      /**
       * @description hosted_view opens a new tab; popup renders as a bottom sheet (mobile) or modal (desktop).
       * @enum {string}
       */
      view_type?: 'hosted_view' | 'popup';
      /** @description Set to 0 to route through Checkout service when the profile also has QR Payment API enabled. */
      payment_gate?: number;
      /** @description Base64-encoded JSON array of {acc, amt} splitting the payment across up to 10 destination accounts (error 25 if exceeded). Accounts must be whitelisted first (error 37). */
      payout?: string;
      /** @description Base64-encoded JSON, currently only used for WeChat Mini Program (wechat_sub_appid, wechat_sub_openid). */
      additional_params?: string;
      /** @description Minutes before the payment link expires. Min 3, max 43200 (30 days). Below 3 is rejected (error 69). Behavior on expiry differs by method: ABA PAY/Card simply fail; KHQR reverses funds to the payer; WeChat/Alipay do not reverse. */
      lifetime?: number;
      /** @description Required when payment_option=google_pay and the merchant manages payment-method selection itself. */
      google_pay_token?: string;
      /** @description base64(HMAC-SHA512(concat_in_x-hmac-fields-order, api_key)). See operation-level x-hmac-fields for the exact field order — it is NOT alphabetical and NOT the same as check/close-transaction. */
      hash: string;
    };
    /** @description Returned instead of HTML when payment_option=abapay_khqr_deeplink. */
    PurchaseQrResponse: {
      /** @description Raw KHQR payload string, scannable by any KHQR-member banking app. */
      qr_string?: string;
      /** @description Deeplink that opens ABA Mobile directly to the pre-filled payment. */
      abapay_deeplink?: string;
      /** @description Hosted URL rendering the QR code as an image/page, for platforms that can't render qr_string themselves. */
      checkout_qr_url?: string;
    };
    /** @description purchase's JSON error shape (distinct from the HTML success path). Non-exhaustive: purchase alone defines ~80 distinct error codes (wrong hash, invalid amount, currency not allowed, payout validation, Google Pay token failures, etc.) — pull the full table from the scraped spec into your SDK's error-code enum rather than hand-copying a subset here; this skeleton intentionally does not restate all ~80 to keep the spec reviewable, but the generated client MUST surface `code` typed, not just `message` stringly. */
    ErrorStatus: {
      status: {
        code: string;
        message: string;
      };
    };
    /** @description Shared shape for check-transaction and close-transaction — both sign only these 3 fields (see per-operation x-hmac-fields). */
    TranLookupRequest: {
      /** @description UTC request timestamp, format YYYYMMDDHHmmss. */
      req_time: string;
      /** @description Merchant key issued by ABA Bank. */
      merchant_id: string;
      /** @description The original purchase transaction id to look up or close. */
      tran_id: string;
      /** @description base64(HMAC-SHA512(req_time + merchant_id + tran_id, api_key)). */
      hash: string;
    };
    StatusBlock: {
      /** @description Endpoint-specific status code. NOTE: check-transaction and close-transaction each define their own code space (e.g. "00" success vs "0" on purchase-family errors) — do not assume a single shared enum across endpoints; encode per-operation code tables separately in the generated SDK's error types. */
      code: string;
      /** @description Human-readable detail for `code`. */
      message: string;
      /** @description Echoes the transaction id the status applies to. */
      tran_id?: string;
    };
    /**
     * @example {
     *       "data": {
     *         "payment_status_code": 0,
     *         "payment_status": "APPROVED",
     *         "total_amount": 10,
     *         "original_amount": 10,
     *         "refund_amount": 0,
     *         "discount_amount": 0,
     *         "payment_amount": 10,
     *         "payment_currency": "USD",
     *         "apv": "619195",
     *         "transaction_date": "2025-02-13 06:56:00"
     *       },
     *       "status": {
     *         "code": "00",
     *         "message": "Success!",
     *         "tran_id": "17394277693"
     *       }
     *     }
     */
    CheckTransactionResponse: {
      /** @description Present on successful lookup (status.code == "00"). */
      data?: {
        /** @description 0=APPROVED/PRE-AUTH, 2=PENDING, 3=DECLINED, 4=REFUNDED, 7=CANCELLED */
        payment_status_code?: number;
        /** @enum {string} */
        payment_status?: 'APPROVED' | 'PRE-AUTH' | 'REFUNDED' | 'PENDING' | 'DECLINED' | 'CANCELLED';
        /** @description Amount due after discount. */
        total_amount?: number;
        original_amount?: number;
        /** @description Sum of all refunds issued against this transaction. */
        refund_amount?: number;
        /** @description In the original transaction's currency. */
        discount_amount?: number;
        /** @description Amount actually paid by the customer. */
        payment_amount?: number;
        payment_currency?: string;
        /** @description Transaction approval code. */
        apv?: string;
        /** @description Timestamp the transaction was created in the payment gateway. */
        transaction_date?: string;
      };
      status: components['schemas']['StatusBlock'];
    };
    CloseTransactionResponse: {
      status: components['schemas']['StatusBlock'];
    };
    /** @description One entry in a transaction's operation history (capture, pre-auth completion/cancellation, refund). */
    TransactionOperation: {
      /** @enum {string} */
      status?: 'Completed' | 'Pre-Auth' | 'Completed Pre-Auth' | 'Cancelled Pre-Auth' | 'Refunded';
      /** @description Amount associated with this specific operation, not the transaction total. */
      amount?: number;
      /** @description Timestamp this operation occurred. */
      transaction_date?: string;
      /** @description Core-banking booking entry id — populated for ABA PAY operations only, blank otherwise. */
      bank_ref?: string;
    };
    /** @description Response for getTransactionDetail. NOT intended for real-time polling — see rate-limit note on the operation (10 req/min, not raisable). */
    TransactionDetailResponse: {
      /** @description Present when status.code == "00". */
      data?: {
        /** @description Echoes the requested tran_id. */
        transaction_id?: string;
        /** @description 0=APPROVED/PRE-AUTH, 2=PENDING, 3=DECLINED, 4=REFUNDED, 7=CANCELLED */
        payment_status_code?: number;
        /** @enum {string} */
        payment_status?: 'APPROVED' | 'PRE-AUTH' | 'PENDING' | 'DECLINED' | 'REFUNDED' | 'CANCELLED';
        /** @description Before discount. */
        original_amount?: number;
        original_currency?: string;
        /** @description Amount actually paid by the customer. */
        payment_amount?: number;
        payment_currency?: string;
        /** @description Amount due after discount. */
        total_amount?: number;
        /** @description Total refunded to date. */
        refund_amount?: number;
        discount_amount?: number;
        /** @description Transaction approval code. */
        apv?: string;
        transaction_date?: string;
        /** @description Payer first name. */
        first_name?: string;
        /** @description Payer last name. */
        last_name?: string;
        email?: string;
        phone?: string;
        /** @description ABA core-banking booking entry reference. */
        bank_ref?: string;
        /** @enum {string} */
        payment_type?: 'ABA Pay' | 'Alipay' | 'Wechat' | 'KHQR' | 'VISA' | 'MC' | 'JCB' | 'CUP';
        /** @description Masked account number or card PAN. */
        payer_account?: string;
        /** @description ABA Bank for ABA PAY, or issuer bank for KHQR. */
        bank_name?: string;
        /** @enum {string} */
        card_source?: 'ONUS' | 'OFFUS_DOMESTIC' | 'OFFUS_INTERNATIONAL';
        /** @description Full operation history for this transaction. */
        transaction_operations?: components['schemas']['TransactionOperation'][];
      };
      /** @description code space for this endpoint: "00" success, "5" wrong hash (note: NOT "1" as in check/close-transaction — do not assume a shared numeric code space across endpoints), "6" transaction not found, "8" invalid merchant profile, "11" internal server error, "429" rate limit exceeded. */
      status: components['schemas']['StatusBlock'];
    };
    /** @description All filter fields are optional but each still occupies a fixed position in the HMAC input per x-hmac-fields on the operation — pass them as null/empty rather than omitting the key. */
    TransactionListRequest: {
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      req_time: string;
      merchant_id: string;
      /** @description Format YYYY-MM-DD HH:mm:ss. Defaults to today 00:00:00 if omitted. */
      from_date?: string | null;
      /** @description Format YYYY-MM-DD HH:mm:ss. Defaults to today 23:59:59 if omitted. Date range capped at 3 days total. */
      to_date?: string | null;
      from_amount?: number | null;
      to_amount?: number | null;
      /** @description Comma-separated for multiple values. Case-insensitive. One of APPROVED, PRE-AUTH, REFUNDED, PENDING, DECLINED, CANCELLED. */
      status?: string | null;
      /** @default 1 */
      page: string;
      /**
       * @description Max 1000 records per page.
       * @default 40
       */
      pagination: string;
      hash: string;
    };
    /** @description Same shape as TransactionDetailResponse.data minus transaction_operations (no per-item history in list view). */
    TransactionListItem: {
      transaction_id?: string;
      transaction_date?: string;
      apv?: string;
      /** @enum {string} */
      payment_status?: 'APPROVED' | 'PRE-AUTH' | 'REFUNDED' | 'PENDING' | 'DECLINED' | 'CANCELLED';
      payment_status_code?: number;
      original_amount?: number;
      /** @enum {string} */
      original_currency?: 'KHR' | 'USD';
      total_amount?: number;
      discount_amount?: number;
      refund_amount?: number;
      payment_amount?: number;
      payment_currency?: string;
      /** @description Only present if enabled on the merchant profile. */
      first_name?: string;
      /** @description Only present if enabled on the merchant profile. */
      last_name?: string;
      /** @description Only present if enabled on the merchant profile. */
      email?: string;
      /** @description Only present if enabled on the merchant profile. */
      phone?: string;
      /** @description Only present if enabled on the merchant profile. */
      bank_ref?: string;
      payer_account?: string;
      bank_name?: string;
      /** @enum {string} */
      card_source?: 'ONUS' | 'OFFUS_DOMESTIC' | 'OFFUS_INTERNATIONAL';
      /**
       * @description N/A for transactions still pending payment.
       * @enum {string}
       */
      payment_type?: 'N/A' | 'ABA Pay' | 'Alipay' | 'Wechat' | 'KHQR' | 'VISA' | 'MC' | 'JCB' | 'CUP';
    };
    TransactionListResponse: {
      data?: components['schemas']['TransactionListItem'][];
      /** @description Current page index. */
      page?: string;
      /** @description Records per page (max 1000). */
      pagination?: string;
      /** @description code space: "00" success, "1" wrong hash, "8" invalid merchant profile, "11" internal server error, "429" rate limit exceeded (50 req/min on this endpoint). */
      status: components['schemas']['StatusBlock'];
    };
    /** @description NOTE the field name is `request_time`, not `req_time` as on every other endpoint in this spec — see info.description item 8. */
    RefundRequest: {
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      request_time: string;
      merchant_id: string;
      /** @description Base64 of RSA-encrypted, chunked JSON {mc_id, tran_id, refund_amount}. See x-merchant-auth-encryption on the refund operation for the exact construction process and required credential (a separate RSA public key from ABA Bank, distinct from the HMAC api_key). */
      merchant_auth: string;
      /** @description base64(HMAC-SHA512(request_time + merchant_id + merchant_auth, api_key)). */
      hash: string;
    };
    RefundResponse: {
      /**
       * Format: double
       * @description Amount after any discount, e.g. $20 purchase with $2 discount -> grand_total $18.
       */
      grand_total?: number;
      /**
       * Format: double
       * @description Cumulative refunded amount across all partial refunds issued so far.
       */
      total_refunded?: number;
      /** @description Original transaction currency. */
      currency?: string;
      /** @description REFUNDED for both full and partial refunds. */
      transaction_status?: string;
      /** @description Distinct, alphanumeric code space unique to this endpoint — do not reuse StatusBlock's assumption of numeric-string codes. Notable codes: 00 success, PTL02 invalid hash, PTL37 refund exceeds original amount, PTL57/PTL58 unable/failed to refund, PTL168 concurrent request rejected, PTL181 insufficient available balance. */
      status: {
        code: string;
        message: string;
      };
    };
    ExchangeRateRequest: {
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      req_time: string;
      merchant_id: string;
      /** @description base64(HMAC-SHA512(req_time + merchant_id, api_key)) — only 2 fields, the shortest hash input in this API surface. */
      hash: string;
    };
    CurrencyRate: {
      /** @description Sell rate, as a decimal string. */
      sell: string;
      /** @description Buy rate, as a decimal string. */
      buy: string;
    };
    /** @description The vendor's own schema listed an inconsistent `required` array under exchange_rates (omitting some currencies present in `properties`) — treated as a docs artifact and modeled here via additionalProperties instead of a hardcoded required list, since the actual currency set PayWay returns may change over time without notice. */
    ExchangeRateResponse: {
      status: {
        /** @description 00 success, 1 wrong hash, 26 invalid merchant profile. */
        code: string;
        message: string;
      };
      /** @description Keyed by lowercase ISO currency code (observed: aud, sgd, eur, gbp, myr, thb, hkd, cny, cad, krw, jpy, vnd). Modeled with additionalProperties rather than enumerating every key as required, since PayWay could add/remove currencies. */
      exchange_rates: {
        [key: string]: components['schemas']['CurrencyRate'];
      };
    };
    LinkAccountRequest: {
      /** @description Unique request identifier generated by the merchant. */
      request_id: string;
      /** @description UTC timestamp, format YYYYMMDDHHmmss. */
      request_time: string;
      /** @description Merchant key issued by ABA Bank. */
      merchant_id: string;
      /** @description Customer token identifier — merchant-side unique ID for the customer. */
      ctid?: string;
      /** @description Base64-encoded JSON {ios_scheme, android_scheme} for mobile app integration. */
      return_deeplink?: string;
      /**
       * @description Defines who triggers transactions and whether the amount is fixed or variable. CITR = Customer-Initiated Token Registration, MITR = Merchant-Initiated Token Registration.
       * @enum {string}
       */
      token_flag?:
        | 'CITR_FIX'
        | 'CITR_FLEX'
        | 'MITR_FIX'
        | 'MITR_FLEX'
        | 'CITI_FIX'
        | 'CITI_FLEX'
        | 'MITU_FIX'
        | 'MITU_FLEX';
      /** @enum {string} */
      currency?: 'KHR' | 'USD';
      /** @description URL where PayWay sends the account details and token after linking. */
      callback_url?: string;
      /** @description base64(HMAC-SHA512(concat_in_x-hmac-fields-order, api_key)). */
      hash: string;
    };
    LinkAccountResponse: {
      status?: {
        code?: string;
        message?: string;
      };
      /** @description QR code payload for scanning. */
      qr_string?: string;
      /** @description Deeplink to open ABA Mobile. */
      abapay_deeplink?: string;
    };
    LinkCardRequest: {
      request_id: string;
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      request_time: string;
      merchant_id: string;
      /** @description Customer token identifier. */
      ctid?: string;
      return_deeplink?: string;
      /** @enum {string} */
      token_flag?:
        | 'CITR_FIX'
        | 'CITR_FLEX'
        | 'MITR_FIX'
        | 'MITR_FLEX'
        | 'CITI_FIX'
        | 'CITI_FLEX'
        | 'MITU_FIX'
        | 'MITU_FLEX';
      /**
       * @description Required for Link Card. Billing frequency.
       * @enum {string}
       */
      frequency?: '1W' | '1M' | '2M';
      /** @description Base64-encoded callback URL. */
      return_url?: string;
      callback_url?: string;
      hash: string;
    };
    LinkCardResponse: {
      status?: {
        code?: string;
        message?: string;
      };
    };
    CofPaymentRequest: {
      request_id: string;
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      request_time: string;
      merchant_id: string;
      /** @description Merchant-generated unique transaction identifier. */
      tran_id: string;
      /** @description Payment amount. */
      amount: number;
      /** @description Token from link-account or link-card. */
      pwt?: string;
      /** @description Customer token identifier. */
      ctid?: string;
      /** @enum {string} */
      token_flag?:
        | 'CITR_FIX'
        | 'CITR_FLEX'
        | 'MITR_FIX'
        | 'MITR_FLEX'
        | 'CITI_FIX'
        | 'CITI_FLEX'
        | 'MITU_FIX'
        | 'MITU_FLEX';
      /** @enum {string} */
      currency?: 'KHR' | 'USD';
      callback_url?: string;
      hash: string;
    };
    CofPaymentResponse: {
      status?: {
        code?: string;
        message?: string;
        tran_id?: string;
      };
    };
    RenewTokenRequest: {
      request_id: string;
      request_time: string;
      merchant_id: string;
      ctid: string;
      pwt: string;
      hash: string;
    };
    RenewTokenResponse: {
      status?: {
        code?: string;
        message?: string;
      };
      /** @description New payment token replacing the old one. */
      new_token?: string;
    };
    GetTokenDetailsRequest: {
      request_id: string;
      request_time: string;
      merchant_id: string;
      ctid: string;
      pwt: string;
      hash: string;
    };
    GetTokenDetailsResponse: {
      status?: {
        code?: string;
        message?: string;
      };
      data?: {
        token?: string;
        /** @description ACCOUNT or CARD. */
        token_type?: string;
        /** @description Masked account number or card PAN. */
        masked_account?: string;
        token_status?: string;
        expiry_date?: string;
      };
    };
    RemoveTokenRequest: {
      request_id: string;
      request_time: string;
      merchant_id: string;
      ctid: string;
      pwt: string;
      hash: string;
    };
    RemoveTokenResponse: {
      status?: {
        code?: string;
        message?: string;
      };
    };
    GenerateQrRequest: {
      /** @description UTC request timestamp, format YYYYMMDDHHmmss. */
      req_time: string;
      /** @description Merchant key issued by ABA Bank. */
      merchant_id: string;
      /** @description Merchant-generated unique transaction identifier. */
      tran_id: string;
      /** @description Payment amount. */
      amount: number;
      /** @enum {string} */
      purchase_type: 'purchase';
      /** @example abapay_khqr */
      payment_option: string;
      /** @description Base64-encoded callback URL. */
      callback_url: string;
      /** @enum {string} */
      currency: 'KHR' | 'USD';
      /** @example template2 */
      qr_image_template: string;
      /** @description base64(HMAC-SHA512(concat_in_x-hmac-fields-order, api_key)). */
      hash: string;
      /** @description Transaction lifetime in minutes. Default: 30 days. Minimum: 3 mins. Maximum: 120 days (172800 mins). */
      lifetime: number;
    };
    GenerateQrResponse: {
      /** @description Raw KHQR payload string, scannable by any KHQR-member banking app. */
      qrString?: string;
      /** @description Data URL containing the rendered QR PNG image. */
      qrImage?: string;
    };
    /** @description Uses RSA-encrypted merchant_auth containing transaction details. See x-merchant-auth-encryption on the operation for encryption process. Sandbox-verified: currency and return_url are REQUIRED inside merchant_auth (PTL04 "Parameter validation required" when omitted). */
    CreatePaymentLinkRequest: {
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      request_time: string;
      /** @description Merchant key issued by ABA Bank. */
      merchant_id: string;
      /** @description Base64 of RSA-encrypted, chunked JSON containing transaction details (title, amount, currency, description, payment_limit, return_url, merchant_ref_no, expired_date). */
      merchant_auth: string;
      /** @description base64(HMAC-SHA512(request_time + merchant_id + merchant_auth, api_key)). */
      hash: string;
    };
    PaymentLinkStatus: {
      code?: string;
      message?: string;
      tran_id?: string;
      lang?: string;
      trace_id?: string;
    };
    /** @description A payment link resource as returned by the create and detail endpoints (sandbox-verified shape). */
    PaymentLink: {
      /** @description Payment link id used with the detail endpoint (e.g. "zX71gfZgVme0juZANHfZMA=="). NOT the slug in the payment_link URL. */
      id?: string;
      title?: string;
      image?: {
        image?: string;
        filename?: string;
        size?: number;
      };
      /** @description Amount as a string (e.g. "0.02"). */
      amount?: string;
      /** @enum {string} */
      currency?: 'USD' | 'KHR';
      /** @description Link status (e.g. OPEN). */
      status?: string;
      description?: string;
      payment_limit?: number;
      total_amount_org?: number;
      total_refund?: number;
      total_amount?: number;
      total_trxn?: number;
      /** @description YYYY-MM-DD HH:mm:ss */
      created_at?: string;
      /** @description YYYY-MM-DD HH:mm:ss */
      updated_at?: string;
      /** @description Epoch seconds when set; empty string or "0" when unset. */
      expired_date?: number | string;
      /** @description Decoded callback URL. */
      return_url?: string;
      merchant_ref_no?: string;
      outlet_id?: string;
      outlet_name?: string;
      /** @description Payout details (null when none). */
      payout?: unknown;
      /** @description Hosted checkout URL to share with customers (e.g. https://link-sandbox.payway.com.kh/ABAPAYzC80644N). */
      payment_link?: string;
    };
    CreatePaymentLinkResponse: {
      status?: components['schemas']['PaymentLinkStatus'];
      /** @description Numeric gateway transaction id (also present as a string in status.tran_id). */
      tran_id?: number;
      data?: components['schemas']['PaymentLink'];
    };
    GetPaymentLinkDetailsRequest: {
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      request_time: string;
      merchant_id: string;
      /** @description RSA-encrypted JSON {mc_id, id}. */
      merchant_auth: string;
      /** @description base64(HMAC-SHA512(request_time + merchant_id + merchant_auth, api_key)). */
      hash: string;
    };
    GetPaymentLinkDetailsResponse: {
      status?: components['schemas']['PaymentLinkStatus'];
      /** @description Numeric gateway transaction id (also present as a string in status.tran_id). */
      tran_id?: number;
      data?: components['schemas']['PaymentLink'];
    };
    /** @description Uses RSA-encrypted merchant_auth. NOTE: uses request_time (not req_time), same convention as the Refund endpoint. */
    CompletePreAuthRequest: {
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      request_time: string;
      merchant_id: string;
      /** @description Base64 of RSA-encrypted JSON {mc_id, tran_id, complete_amount, payout?}. */
      merchant_auth: string;
      /** @description base64(HMAC-SHA512(request_time + merchant_id + merchant_auth, api_key)). */
      hash: string;
    };
    CompletePreAuthResponse: {
      status?: {
        code: string;
        message: string;
      };
      /** @description Updated status after completion (e.g., APPROVED). */
      transaction_status?: string;
      total_amount?: number;
    };
    CancelPreAuthRequest: {
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      request_time: string;
      merchant_id: string;
      /** @description Base64 of RSA-encrypted JSON {mc_id, tran_id}. */
      merchant_auth: string;
      /** @description base64(HMAC-SHA512(request_time + merchant_id + merchant_auth, api_key)). */
      hash: string;
    };
    CancelPreAuthResponse: {
      status?: {
        code: string;
        message: string;
      };
      /** @description Updated status after cancellation (e.g., CANCELLED). */
      transaction_status?: string;
    };
    PayoutRequest: {
      /** @description Merchant key issued by ABA Bank. */
      merchant_id: string;
      /** @description Merchant-generated unique payout transaction identifier. */
      tran_id: string;
      /** @description Payout amount. */
      amount: number;
      /** @description Base64 of RSA-encrypted JSON array of {account, amount}. */
      beneficiaries: string;
      /** @enum {string} */
      currency: 'KHR' | 'USD';
      /** @description JSON string associated with the payout. */
      custom_fields?: string;
      /** @description hex(HMAC-SHA512(merchant_id + tran_id + beneficiaries + amount + custom_fields + currency, api_key)). */
      hash: string;
    };
    PayoutResponse: {
      status?: {
        code: string;
        message: string;
        tran_id?: string;
      };
      /** @description Core-banking reference for the payout transaction. */
      bank_ref?: string;
    };
    UpdateBeneficiaryStatusRequest: {
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      request_time: string;
      merchant_id: string;
      /** @description Base64 of RSA-encrypted JSON {mc_id, payee, status}, where status is 0 or 1. */
      merchant_auth: string;
      /** @description base64(HMAC-SHA512(request_time + merchant_auth, api_key)). */
      hash: string;
    };
    BeneficiaryResponse: {
      status?: {
        code: string;
        message: string;
      };
    };
    AddBeneficiaryRequest: {
      /** @description UTC timestamp, YYYYMMDDHHmmss. */
      request_time: string;
      merchant_id: string;
      /** @description Base64 of RSA-encrypted JSON {mc_id, payee}. */
      merchant_auth: string;
      /** @description base64(HMAC-SHA512(request_time + merchant_auth, api_key)). */
      hash: string;
    };
    GetTransactionsByMcRefRequest: {
      /**
       * @description UTC timestamp, format YYYYMMDDHHmmss.
       * @example 20250213084236
       */
      req_time: string;
      /**
       * @description Merchant key issued by ABA Bank.
       * @example ec000002
       */
      merchant_id: string;
      /**
       * @description Merchant reference number.
       * @example 17394277693
       */
      merchant_ref: string;
      /** @description base64(HMAC-SHA512(req_time + merchant_id + merchant_ref, api_key)). */
      hash: string;
    };
    KhqrTransaction: {
      transaction_id?: string;
      transaction_date?: string;
      bank_ref?: string;
      apv?: string;
      discount_amount?: number;
      payment_status?: string;
      payment_amount?: number;
      payment_currency?: string;
      payment_type?: string;
      payer_account?: string;
      total_amount?: number;
      original_amount?: number;
      original_currency?: string;
      payment_status_code?: number;
      bank_name?: string;
      refund_amount?: number;
      merchant_ref?: string;
    };
    GetTransactionsByMcRefResponse: {
      /** @description 0=Success, 1=Wrong hash, 8=Invalid merchant profile, 11=Internal server error. */
      status?: number;
      transactions?: components['schemas']['KhqrTransaction'][];
    };
    /** @description Body shape is NOT fixed — PayWay states additional fields may be present depending on payment method. Treat unknown keys as pass-through when computing the signature (item 3 in info.description sorts ALL present keys, not a fixed subset). */
    PaymentCallbackBody: {
      /** @description The tran_id supplied on the original purchase call. */
      tran_id: string;
      /** @description Transaction approval code. */
      apv: string;
      /** @description Payment status for this callback. */
      status: string;
      /** @description Echoes the return_params value from the original purchase request, if any was supplied. */
      return_params?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  createPurchase: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['PurchaseRequest'];
      };
    };
    responses: {
      /** @description Hosted checkout page (HTML) or a JSON QR payload, depending on payment_option. Response codes for the JSON error case are enumerated in ErrorStatus. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/html': string;
          'application/json': components['schemas']['PurchaseQrResponse'] | components['schemas']['ErrorStatus'];
        };
      };
    };
  };
  checkTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "req_time": "20250213065545",
         *       "merchant_id": "ec000002",
         *       "tran_id": "17394277693",
         *       "hash": "4slqXzgVig09Hf...2vgALgdENA=="
         *     }
         */
        'application/json': components['schemas']['TranLookupRequest'];
      };
    };
    responses: {
      /** @description Transaction status payload */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CheckTransactionResponse'];
        };
      };
    };
  };
  closeTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "req_time": "20241022053608",
         *       "merchant_id": "lavacafe",
         *       "tran_id": "1729573626",
         *       "hash": "ln9Td4JiGPc...R6y2tmUoF2NERNaQ=="
         *     }
         */
        'application/json': components['schemas']['TranLookupRequest'];
      };
    };
    responses: {
      /** @description Close confirmation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CloseTransactionResponse'];
        };
      };
    };
  };
  getTransactionDetail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "req_time": "20250213084236",
         *       "merchant_id": "ec000002",
         *       "tran_id": "17394277693",
         *       "hash": "QskVi2gEctW...j7Td6kEi/KLPvGcK3ZiA=="
         *     }
         */
        'application/json': components['schemas']['TranLookupRequest'];
      };
    };
    responses: {
      /** @description Full transaction detail with operation history */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionDetailResponse'];
        };
      };
    };
  };
  getTransactionList: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "req_time": "20250213081756",
         *       "merchant_id": "ec000002",
         *       "from_date": null,
         *       "to_date": null,
         *       "from_amount": "0.01",
         *       "to_amount": "1000",
         *       "status": null,
         *       "page": "1",
         *       "pagination": "40",
         *       "hash": "o1mDvIjTyzoFcN7zvm7...aUYAGXjsx4Ej0E6P2CoxtOQ=="
         *     }
         */
        'application/json': components['schemas']['TransactionListRequest'];
      };
    };
    responses: {
      /** @description Paginated transaction list for the outlet */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TransactionListResponse'];
        };
      };
    };
  };
  refundTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "request_time": "20200728093403",
         *       "merchant_id": "ec000002",
         *       "merchant_auth": "[REMOVED-HISTORICAL-c2a924c7bffe]",
         *       "hash": "3nd/2Z4g45...wnA2WA/M/Qg=="
         *     }
         */
        'application/json': components['schemas']['RefundRequest'];
      };
    };
    responses: {
      /** @description Refund result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RefundResponse'];
        };
      };
    };
  };
  getExchangeRate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        /**
         * @example {
         *       "req_time": "20250212104216",
         *       "merchant_id": "ec000002",
         *       "hash": "2P+5NrSb5g2XyITaxttsnjW...JVKguqghoQrq4y4C3tbUiA=="
         *     }
         */
        'application/json': components['schemas']['ExchangeRateRequest'];
      };
    };
    responses: {
      /** @description Current exchange rates keyed by lowercase ISO currency code */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExchangeRateResponse'];
        };
      };
    };
  };
  linkAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LinkAccountRequest'];
      };
    };
    responses: {
      /** @description QR code or deeplink for account linking */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LinkAccountResponse'];
        };
      };
    };
  };
  linkCard: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['LinkCardRequest'];
      };
    };
    responses: {
      /** @description Hosted checkout for card linking */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LinkCardResponse'];
        };
      };
    };
  };
  cofPayment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CofPaymentRequest'];
      };
    };
    responses: {
      /** @description Payment result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CofPaymentResponse'];
        };
      };
    };
  };
  renewToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RenewTokenRequest'];
      };
    };
    responses: {
      /** @description New token details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RenewTokenResponse'];
        };
      };
    };
  };
  getTokenDetails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GetTokenDetailsRequest'];
      };
    };
    responses: {
      /** @description Token details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetTokenDetailsResponse'];
        };
      };
    };
  };
  removeToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RemoveTokenRequest'];
      };
    };
    responses: {
      /** @description Token removal result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RemoveTokenResponse'];
        };
      };
    };
  };
  generateQr: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GenerateQrRequest'];
      };
    };
    responses: {
      /** @description QR code payload and deeplinks */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenerateQrResponse'];
        };
      };
    };
  };
  createPaymentLink: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePaymentLinkRequest'];
      };
    };
    responses: {
      /** @description Payment link creation result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreatePaymentLinkResponse'];
        };
      };
    };
  };
  getPaymentLinkDetails: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GetPaymentLinkDetailsRequest'];
      };
    };
    responses: {
      /** @description Payment link details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetPaymentLinkDetailsResponse'];
        };
      };
    };
  };
  completePreAuth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompletePreAuthRequest'];
      };
    };
    responses: {
      /** @description Pre-auth completion result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CompletePreAuthResponse'];
        };
      };
    };
  };
  cancelPreAuth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CancelPreAuthRequest'];
      };
    };
    responses: {
      /** @description Pre-auth cancellation result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CancelPreAuthResponse'];
        };
      };
    };
  };
  payout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PayoutRequest'];
      };
    };
    responses: {
      /** @description Payout result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PayoutResponse'];
        };
      };
    };
  };
  updateBeneficiaryStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateBeneficiaryStatusRequest'];
      };
    };
    responses: {
      /** @description Beneficiary status update result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BeneficiaryResponse'];
        };
      };
    };
  };
  addBeneficiary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddBeneficiaryRequest'];
      };
    };
    responses: {
      /** @description Beneficiary addition result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BeneficiaryResponse'];
        };
      };
    };
  };
  getTransactionsByMerchantRef: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GetTransactionsByMcRefRequest'];
      };
    };
    responses: {
      /** @description Matching transactions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GetTransactionsByMcRefResponse'];
        };
      };
    };
  };
  paymentCallback: {
    parameters: {
      query?: never;
      header: {
        /** @description Base64 HMAC-SHA512 of the sorted-and-concatenated response body values, keyed by the merchant's api_key. */
        'X-PAYWAY-HMAC-SHA512': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PaymentCallbackBody'];
      };
    };
    responses: {
      /** @description Acknowledge receipt (merchant endpoint's own response, not PayWay's) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
