/**
 * Knowledge-corpus access for the `docs` command and the `query_knowledge`
 * agent tool. The corpus is GENERATED by `npm run sync:knowledge`
 * (scripts/sync-knowledge.mjs) into `knowledge/` and shipped via package.json
 * "files" — generated files are never edited by hand, and
 * src/__tests__/knowledge.test.ts fails when they drift from their sources.
 */
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

export interface KnowledgeTopic {
  topic: string;
  title: string;
  description: string;
  source: string;
  file: string;
  bytes: number;
}

export interface KnowledgeManifest {
  schema: string;
  generator: string;
  topics: KnowledgeTopic[];
}

export interface KnowledgeHit {
  topic: string;
  file: string;
  line: number;
  text: string;
}

export type ReadTopicResult =
  | { status: 'ok'; topic: KnowledgeTopic; content: string }
  | { status: 'missing' }
  | { status: 'ambiguous'; matches: KnowledgeTopic[] };

/**
 * Find the knowledge directory: explicit argument wins, then the
 * PAYWAY_KNOWLEDGE_DIR override, then the packaged location relative to the
 * executable (src/cli.ts in dev → repo root; dist/cli.js → package root),
 * then ./knowledge from the working directory (vitest).
 */
export function resolveKnowledgeDir(explicit?: string): string | null {
  const exeDir = path.dirname(process.argv[1] ?? process.cwd());
  const candidates = [
    explicit,
    process.env.PAYWAY_KNOWLEDGE_DIR,
    path.join(exeDir, '..', 'knowledge'),
    path.join(process.cwd(), 'knowledge'),
  ];
  for (const candidate of candidates) {
    if (candidate && existsSync(path.join(candidate, 'MANIFEST.json'))) return candidate;
  }
  return null;
}

export function loadManifest(dir: string): KnowledgeManifest | null {
  try {
    const manifest = JSON.parse(readFileSync(path.join(dir, 'MANIFEST.json'), 'utf8')) as KnowledgeManifest;
    return manifest.schema === 'knowledge-manifest/v1' ? manifest : null;
  } catch {
    return null;
  }
}

export function listTopics(explicitDir?: string): { dir: string; topics: KnowledgeTopic[] } | null {
  const dir = resolveKnowledgeDir(explicitDir);
  if (!dir) return null;
  const manifest = loadManifest(dir);
  if (!manifest) return null;
  return { dir, topics: manifest.topics };
}

const normalizeSlug = (slug: string) => slug.toLowerCase().replace(/\.(md|json)$/i, '');

/**
 * Read one topic. Accepts the topic slug, the packaged file name
 * ("quickstart.md"), or a unique prefix ("pay" → payment-link,
 * payment-…? ambiguous when several topics share the prefix).
 */
export function readTopic(slug: string, explicitDir?: string): ReadTopicResult | null {
  const found = listTopics(explicitDir);
  if (!found) return null;
  const { dir, topics } = found;
  const wanted = normalizeSlug(slug);
  const exact = topics.find((t) => t.topic === wanted || normalizeSlug(t.file) === wanted);
  const topic = exact ?? (() => {
    const prefixed = topics.filter((t) => t.topic.startsWith(wanted));
    return prefixed.length === 1 ? prefixed[0] : undefined;
  })();
  if (!topic) {
    const matches = topics.filter((t) => t.topic.startsWith(wanted));
    if (matches.length > 1) return { status: 'ambiguous', matches };
    return { status: 'missing' };
  }
  const file = path.join(dir, topic.file);
  if (!existsSync(file)) return { status: 'missing' };
  return { status: 'ok', topic, content: readFileSync(file, 'utf8') };
}

/** Case-insensitive search across the whole corpus; multi-word queries AND. */
export function searchKnowledge(
  query: string,
  explicitDir?: string,
  max = 40,
): { totalHits: number; truncated: boolean; hits: KnowledgeHit[] } | null {
  const found = listTopics(explicitDir);
  if (!found) return null;
  const terms = query
    .toLowerCase()
    .split(/\s+/)
    .filter((term) => term.length > 0);
  if (terms.length === 0) return { totalHits: 0, truncated: false, hits: [] };
  const hits: KnowledgeHit[] = [];
  for (const topic of found.topics) {
    const content = readFileSync(path.join(found.dir, topic.file), 'utf8');
    const lines = content.split(/\r?\n/);
    for (let i = 0; i < lines.length; i += 1) {
      const line = lines[i].toLowerCase();
      if (terms.every((term) => line.includes(term))) {
        hits.push({ topic: topic.topic, file: topic.file, line: i + 1, text: lines[i].trim().slice(0, 200) });
        if (hits.length >= max) {
          return { totalHits: hits.length, truncated: true, hits };
        }
      }
    }
  }
  return { totalHits: hits.length, truncated: false, hits };
}
